/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import codes.bankalar1;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ozkan
 */
public class Banka_EkleSil extends javax.swing.JFrame {

    /**
     * Creates new form Banka_EkleSil
     */
   
    public Banka_EkleSil() {
        initComponents();
    }
       private String hesapNo;

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField7 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("Hesap Ekle/Sil");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 26, 530, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 0, 530, -1));
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 114, 530, -1));

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 88, 500, -1));
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 57, 530, -1));

        jButton1.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jButton1.setText("Hesap Ekle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, -1));

        jLabel2.setText("Şube              :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 71, -1));

        jLabel3.setText("Banka Adı       :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 3, -1, -1));

        jLabel4.setText("Hesap No       :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 29, -1, -1));

        jLabel5.setText("Iban               :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 91, -1, -1));

        jLabel6.setText("Müşteri No     :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 71, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("TR");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Banka İletişim Bilgileri ");

        jLabel16.setText("(Doldurmak Zorunda Değilsiniz)");

        jLabel17.setText("Telefon Numarası   :");

        jLabel18.setText("Adres                      :");

        jLabel19.setText("Mail Adresi              :");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setAutoscrolls(false);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addGap(0, 89, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jTextField2))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(250, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 400, 450));

        jTabbedPane1.addTab("Hesap Ekle", jPanel1);

        jPanel2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel2ComponentShown(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("Silmek İstediğiniz Hesabı Seçiniz:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jButton2.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jButton2.setText("Hesap Sil");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hesaplar" }));
        jComboBox1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jComboBox1ComponentShown(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 359, -1));
        jPanel2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 930, -1));
        jPanel2.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 930, -1));

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 930, -1));
        jPanel2.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 930, -1));

        jLabel10.setText("Şube              :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 71, -1));

        jLabel11.setText("Hesap No       :");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel12.setText("Iban               :");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel13.setText("Müşteri No     :");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 71, -1));

        jButton3.setText("Güncelle");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 90, 30));

        jButton4.setText("TEMİZLE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 30, -1, -1));

        jTabbedPane1.addTab("Hesap Sil/Güncelle", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        codes.bankalar1 banka = new bankalar1();
        banka.tel=false;banka.mail=false;banka.adres=false;
        banka.setHesap_no(jTextField4.getText());
        banka.setSube(jTextField8.getText());
        banka.setIban_no("TR"+jTextField6.getText());
        banka.setMusteri_no(jTextField5.getText());
        //banka.setCins(jComboBox3.getSelectedItem().toString());
          codes.bankalar1 bn = new codes.bankalar1();
        int bankanu =0; 
            try {
                 bankanu = bn.bankaNoBul(jComboBox2.getSelectedItem().toString());
            } catch (SQLException ex) {
                Logger.getLogger(kasa.class.getName()).log(Level.SEVERE, null, ex);
            }
            banka.setBanka_no(String.valueOf(bankanu));
            if(!jTextField1.getText().equals("")){ 
            banka.setBanka_tel(jTextField1.getText());
            banka.tel=true;
            } 
            if(!jTextArea1.getText().equals("")){
            banka.setBanka_adres(jTextArea1.getText());
            banka.adres=true;
            } 
           
            if(!jTextField2.getText().equals("")){
                banka.setBanka_mail(jTextField2.getText());
                banka.mail=true;
            }
        //banka.setBanka_adi(jComboBox2.getSelectedItem().toString());
        try {
            banka.HesapEkle(banka);
            JOptionPane.showMessageDialog(this, "İşlem Başarılı");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextArea1.setText("");
            jComboBox2.setSelectedIndex(0);
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            
        } catch (SQLException ex) {
            Logger.getLogger(Banka_EkleSil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        codes.bankalar1 bnk = new codes.bankalar1();
        boolean durum=false;
         try {
             durum = bnk.HesapSil(this.hesapNo);
             if(durum){
             jTextField7.setText("");
             jTextField9.setText("");
             jTextField11.setText("");
             jTextField10.setText("");
             jComboBox1.setSelectedIndex(0);
             List<codes.bankalar1> bankalist = null;//
         this.hesapNo = jComboBox1.getSelectedItem().toString();
         String[] dizi = this.hesapNo.split(" - ");
         this.hesapNo = dizi[0];
         try {
             bankalist= new codes.bankalar1().Hesap_bul(this.hesapNo);
         } catch (SQLException ex) {
             Logger.getLogger(Banka_EkleSil.class.getName()).log(Level.SEVERE, null, ex);
         }
         for(int i=0;i<bankalist.size();i++){
         jTextField7.setText(bankalist.get(i).getHesap_no());
         jTextField11.setText(bankalist.get(i).getSube());
         jTextField10.setText(bankalist.get(i).getIban_no());
         jTextField9.setText(bankalist.get(i).getMusteri_no());
         }
             }else{
                 JOptionPane.showMessageDialog(this, "Silinirken hata oldu");
             }
         } catch (SQLException ex) {
             Logger.getLogger(Banka_EkleSil.class.getName()).log(Level.SEVERE, null, ex);
             
             
         }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jPanel2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel2ComponentShown
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jPanel2ComponentShown
    
    private void jComboBox1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jComboBox1ComponentShown
        // TODO add your handling code here:
        
         
    }//GEN-LAST:event_jComboBox1ComponentShown

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        boolean durum = false;
        codes.bankalar1 bnk1 = new codes.bankalar1();
        bnk1.setHesap_no(jTextField7.getText().toString());
        bnk1.setSube(jTextField11.getText().toString());
        bnk1.setIban_no(jTextField10.getText().toString());
        bnk1.setMusteri_no(jTextField9.getText().toString());
         try {
             durum = bnk1.Hesap_guncelle(this.hesapNo);
         } catch (SQLException ex) {
             Logger.getLogger(Banka_EkleSil.class.getName()).log(Level.SEVERE, null, ex);
         }
         
         //----BAŞARILIYSA TEXTBOXLARI GÜNCELLER-----------
         if (durum){
            JOptionPane.showMessageDialog(null, "Kayıt Başarıyla Güncellendi");
            List<codes.bankalar1> bankalist = null;//
            try {
             bankalist= new codes.bankalar1().Hesap_bul(this.hesapNo);
         } catch (SQLException ex) {
             Logger.getLogger(Banka_EkleSil.class.getName()).log(Level.SEVERE, null, ex);
         }
            for(int i=0;i<bankalist.size();i++){
              jTextField7.setText(bankalist.get(i).getHesap_no());
              jTextField11.setText(bankalist.get(i).getSube());
              jTextField10.setText(bankalist.get(i).getIban_no());
              jTextField9.setText(bankalist.get(i).getMusteri_no());
            }
         
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
         List<codes.bankalar1> bankalist = null;//
         this.hesapNo = jComboBox1.getSelectedItem().toString();
         String[] dizi = this.hesapNo.split(" - ");
         this.hesapNo = dizi[0];
         try {
             bankalist= new codes.bankalar1().Hesap_bul(this.hesapNo);
         } catch (SQLException ex) {
             Logger.getLogger(Banka_EkleSil.class.getName()).log(Level.SEVERE, null, ex);
         }
         for(int i=0;i<bankalist.size();i++){
         jTextField7.setText(bankalist.get(i).getHesap_no());
         jTextField11.setText(bankalist.get(i).getSube());
         jTextField10.setText(bankalist.get(i).getIban_no());
         jTextField9.setText(bankalist.get(i).getMusteri_no());
         }
         
    }//GEN-LAST:event_jComboBox1ActionPerformed
    public void bankaEkleSilGetir(){
        this.hesapNo = null;
        //--BANKALAR LİSTESİNİ COMBOBOX2'YE ATAMA--------------
        List<codes.bankalar1> bankalar =null;
            DefaultComboBoxModel comboListBanka = new DefaultComboBoxModel();
        try {
            bankalar = new codes.bankalar1().BankaListesi();
        } catch (SQLException ex) {
            Logger.getLogger(kasa.class.getName()).log(Level.SEVERE, null, ex);
        }
        for(int i=0;i<bankalar.size();i++){
            comboListBanka.addElement(bankalar.get(i).getBankalist_ad());
        }
        jComboBox2.setModel(comboListBanka);
        jComboBox2.repaint();
        
        //-------HESAPLARI LİSTESİNİ COMBOBOX1'E ATAMA--------
        
        List<codes.hesaplar> hesaplist = null;//new ArrayList<>();
        DefaultComboBoxModel combomodel = (DefaultComboBoxModel) jComboBox1.getModel();
        
        try {
            hesaplist = new codes.hesaplar().HesaplarListesi();
        } catch (SQLException ex) {
            Logger.getLogger(kasa.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        for(int n=0;n<hesaplist.size();n++){
            
            String hesapno = hesaplist.get(n).getHesap_no();
            String bankaadi = null;
            try {
                bankaadi = new codes.bankalar1().bankaAdiBul(Integer.parseInt(hesaplist.get(n).getBanka_no()));
            } catch (SQLException ex) {
                Logger.getLogger(kasa.class.getName()).log(Level.SEVERE, null, ex);
            }
            String sube = hesaplist.get(n).getSube();
            String sonuc = hesapno+" - "+sube+" - "+bankaadi;
            combomodel.addElement(sonuc);
        }
        jComboBox1.setModel(combomodel);
        jComboBox1.repaint();
    }
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        this.hesapNo = null;
        bankaEkleSilGetir();
    }//GEN-LAST:event_formComponentShown

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jTextField7.setText("");
        jTextField11.setText("");
        jTextField10.setText("");
        jTextField9.setText("");
        jComboBox1.setSelectedIndex(0);
        this.hesapNo=null;
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Banka_EkleSil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Banka_EkleSil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Banka_EkleSil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Banka_EkleSil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Banka_EkleSil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
