/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import gui.cekler_detay;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.table.TableColumnModel;
/**
 *
 * @author ozkan
 */
public class cekler extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    public cekler() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Çek No", "Banka", "Tutar", "Vade Tarihi", "Yazılma Tarihi", "Gönderen"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTable1ComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jRadioButton1.setText("Eldeki Çekler");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Giden Çekler");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setText("Hepsini Gör");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Excel'e Aktar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(jRadioButton1)
                .addGap(27, 27, 27)
                .addComponent(jRadioButton2)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton3)
                .addContainerGap(447, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addGap(2, 2, 2)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
                // TODO add your handling code here:
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(false);        
        ceklerHepsiniGoster();
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        
        jRadioButton1.setSelected(false);
        jRadioButton3.setSelected(false);
         List<codes.cekler> cekliste = null;//new ArrayList<>();
        DefaultTableModel cektablo1 = (DefaultTableModel) jTable1.getModel();
        cektablo1.getDataVector().clear();
        cektablo1.setRowCount(0);
        List<codes.cekler> cekdetay= null;
        
        try {
            cekliste = new codes.cekler().cek_giden();
        } catch (SQLException ex) {
            Logger.getLogger(cekler.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Vector[] v = new Vector[cekliste.size()];
        for(int n=0;n<cekliste.size();n++){
            v[n] = new Vector();
            v[n].add(cekliste.get(n).getCekno());
            String gidenno = cekliste.get(n).getGidenno();
           try {
                cekdetay = new codes.cekler().cek_detay(cekliste.get(n).getCekno());
            } catch (SQLException ex) {
                Logger.getLogger(cekler.class.getName()).log(Level.SEVERE, null, ex);
            }
            for(int j=0;j<cekdetay.size();j++){
                codes.bankalar1 bnk = new codes.bankalar1();
                String bankaAdi=null; int bankaNo1=0;
                bankaNo1 = Integer.parseInt(cekdetay.get(j).getBanka());
                try {
                   bankaAdi = bnk.bankaAdiBul(bankaNo1);
                } catch (SQLException ex) {
                    Logger.getLogger(cekler.class.getName()).log(Level.SEVERE, null, ex);
                }
            
            v[n].add(bankaAdi);
            v[n].add(cekdetay.get(j).getTutar());
            v[n].add(cekdetay.get(j).getVade_tarih());
            v[n].add(cekdetay.get(j).getYaz_tarih());
            codes.sirketler sirk = new codes.sirketler();
            String gidenad = null;
                try {
                    gidenad = sirk.sirketAdiAl(gidenno);
                } catch (SQLException ex) {
                    Logger.getLogger(cekler.class.getName()).log(Level.SEVERE, null, ex);
                }
                if(gidenad==null || gidenad.length()==0){
                    v[n].add(gidenno);
                }else
                    v[n].add(gidenad);
               
            
        }
            cektablo1.insertRow(n, v[n]);
        
        jTable1.setModel(cektablo1);
         jTable1.repaint();
         
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        jRadioButton2.setSelected(false);
        jRadioButton3.setSelected(false);
        List<codes.cekler> cekliste = null;
        DefaultTableModel cektablo = (DefaultTableModel) jTable1.getModel();
        cektablo.getDataVector().clear();
     
        try {
            cekliste = new codes.cekler().cek_elde();
        } catch (SQLException ex) {
            Logger.getLogger(cekler.class.getName()).log(Level.SEVERE, null, ex);
        }
        List<codes.cekler> cekdetay = null;
        Vector[] v = new Vector[cekliste.size()];
        for(int n=0;n<cekliste.size();n++){
            v[n] = new Vector();
            v[n].add(cekliste.get(n).getCekno());
            String cekNo= cekliste.get(n).getCekno();
            String kurumno = cekliste.get(n).getGelno();
            try {
                cekdetay = new codes.cekler().cek_detay(cekliste.get(n).getCekno());
            } catch (SQLException ex) {
                Logger.getLogger(cekler.class.getName()).log(Level.SEVERE, null, ex);
            }
            for(int j=0;j<cekdetay.size();j++){
                codes.bankalar1 bnk = new codes.bankalar1();
                String bankaAdi=null; int bankaNo1=0;
                bankaNo1 = Integer.parseInt(cekdetay.get(j).getBanka());
                try {
                   bankaAdi = bnk.bankaAdiBul(bankaNo1);
                } catch (SQLException ex) {
                    Logger.getLogger(cekler.class.getName()).log(Level.SEVERE, null, ex);
                }
            v[n].add(bankaAdi);
            v[n].add(cekdetay.get(j).getTutar());
            v[n].add(cekdetay.get(j).getVade_tarih());
            v[n].add(cekdetay.get(j).getYaz_tarih());
            codes.sirketler sk = new codes.sirketler();
            String kurumno1=null;
                try {
                    kurumno1 = sk.sirketAdiAl(kurumno);
                } catch (SQLException ex) {
                    Logger.getLogger(cekler.class.getName()).log(Level.SEVERE, null, ex);
                }
                 if(kurumno1==null || kurumno1.length()==0){
                    v[n].add(kurumno);
                }else
                    v[n].add(kurumno1);
            
            }
            
            cektablo.insertRow(n, v[n]);
        }
        
        jTable1.setModel(cektablo);
         jTable1.repaint();
    }//GEN-LAST:event_jRadioButton1ActionPerformed
    public void ceklerHepsiniGoster(){
         jRadioButton3.setSelected(true);
           jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(false);    
         List<codes.cekler> cekliste = null;//new ArrayList<>();
        DefaultTableModel cektablo = (DefaultTableModel) jTable1.getModel();
        cektablo.getDataVector().clear();
        List<codes.cekler> cekdetay= null;
        
        try {
            cekliste = new codes.cekler().cek_tumu();
        } catch (SQLException ex) {
            Logger.getLogger(cekler.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        Vector[] v = new Vector[cekliste.size()];
        for(int n=0;n<cekliste.size();n++){
            v[n] = new Vector();
            v[n].add(cekliste.get(n).getCekno());
            String cekNo1 = cekliste.get(n).getCekno();
            try {
                cekdetay = new codes.cekler().cek_detay(cekliste.get(n).getCekno());
            } catch (SQLException ex) {
                Logger.getLogger(cekler.class.getName()).log(Level.SEVERE, null, ex);
            }
            for(int j=0;j<cekdetay.size();j++){
                codes.bankalar1 bnk = new codes.bankalar1();
                String bankaAdi=null; int bankaNo1=0;
                bankaNo1 = Integer.parseInt(cekdetay.get(j).getBanka());
                try {
                   bankaAdi = bnk.bankaAdiBul(bankaNo1);
                } catch (SQLException ex) {
                    Logger.getLogger(cekler.class.getName()).log(Level.SEVERE, null, ex);
                }
            v[n].add(bankaAdi);
            v[n].add(cekdetay.get(j).getTutar());
            v[n].add(cekdetay.get(j).getVade_tarih());
            v[n].add(cekdetay.get(j).getYaz_tarih());
            }
            
            //v[n].add(cekliste.get(n).getBanka());
            //v[n].add(cekliste.get(n).getTutar());
            //v[n].add(cekliste.get(n).getVade_tarih());
            //v[n].add(cekliste.get(n).getYaz_tarih());
            
            codes.sirketler srk = new codes.sirketler();
            String kurumNo1 = cekliste.get(n).getGelno();
            String kurumAdi=null;
            try {
                kurumAdi = srk.sirketAdiAl(kurumNo1);
            } catch (SQLException ex) {
                Logger.getLogger(cekler.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(kurumAdi==null || kurumAdi.length()==0){
                    v[n].add(kurumNo1);
                }else
                    v[n].add(kurumAdi);
            v[n].add(kurumAdi);
            cektablo.insertRow(n, v[n]);
        }
        
        jTable1.setModel(cektablo);
         jTable1.repaint();
    }
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        jRadioButton3.setSelected(true);
           jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(false);        
       ceklerHepsiniGoster();
    }//GEN-LAST:event_formComponentShown

    private void jTable1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable1ComponentShown
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jTable1ComponentShown

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
          if (evt.getClickCount() ==2) {
      JTable target = (JTable)evt.getSource();
      int row = target.getSelectedRow();
      int column = target.getSelectedColumn();
        String hesapno = jTable1.getValueAt(row, 0).toString();
       gui.cekler_detay cd = new gui.cekler_detay();
       cd.cekNom = hesapno;
       System.out.println(hesapno+" "+cd.cekNom);
        JFrame fm = new JFrame();
        fm.add(cd.getContentPane());
        fm.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        fm.setVisible(true); fm.revalidate();
        cd.gosterCekDetay();
        fm.repaint();
        
        fm.pack();
        
      // do some action if appropriate column
    }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int returnVal = jFileChooser1.showOpenDialog(this);
         jFileChooser1.setFileSelectionMode(JFileChooser.FILES_ONLY);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = (File) jFileChooser1.getSelectedFile().getAbsoluteFile();
            codes.sirketler ex= new codes.sirketler();
           // File file =new File("C:\\Users\\ozkan\\Desktop\\bankalar.xlsx");
                System.out.println(file);
            
             try {
                 ex.exportTable(jTable1, file);
                 //}      
             } catch (IOException ex1) {
                 Logger.getLogger(KasaListele.class.getName()).log(Level.SEVERE, null, ex1);
         
             }
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public String cekNo;
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cekler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cekler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cekler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cekler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cekler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
