/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fadime
 */
public class hesapdetay extends javax.swing.JFrame {

    /**
     * Creates new form hesapdetay
     */
    public String hesap_no_hesapDetay;
    private static Bankalar atapencere;
    public hesapdetay() {
        
        initComponents();
    }

    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        scrollbar1 = new java.awt.Scrollbar();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Hesap No", "Tarih", "Yatırılan Tutar", "Çekilen Tutar", "Açıklama"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTable1ComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("HESAP ");

        jTextField1.setEnabled(false);
        jTextField1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTextField1ComponentShown(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Şube            :");

        jLabel3.setText("Banka Adı :");

        jLabel4.setText("Bakiye Bilgisi :");

        jTextField2.setEnabled(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setEnabled(false);

        jButton1.setText("Geri Dön");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("IbanNo:");

        jTextField4.setEnabled(false);

        jLabel6.setText("Tarih Arasında Listele:");

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("-");

        try {
            jFormattedTextField3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField3ActionPerformed(evt);
            }
        });

        jButton2.setText("Listele");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Tarihler Arasında Listele");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Temizle");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(21, 21, 21)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3))
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 801, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollbar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jLabel6)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(29, 29, 29)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollbar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void calistir(){
        String a = this.hesap_no_hesapDetay;
        
        hesapdetay hsp = new hesapdetay();
        List<codes.bankalar1> hesaplist = null;//new ArrayList<>();
        DefaultTableModel hesaptablo = (DefaultTableModel) jTable1.getModel();
        hesaptablo.getDataVector().clear();
        List<codes.bankalar1> hesapcikan = null;
        try {
            hesapcikan = new codes.bankalar1().hesapDetayHepsi(a);
        } catch (SQLException ex) {
            Logger.getLogger(hesapdetay.class.getName()).log(Level.SEVERE, null, ex);
        }
        Vector[] n = new Vector[hesapcikan.size()];
        for(int i =0;i<hesapcikan.size();i++){
            n[i] = new Vector();
            n[i].add(a);
            n[i].add(hesapcikan.get(i).getTarihCikan());
            n[i].add(hesapcikan.get(i).getCikanMiktar());
            n[i].add("");
            n[i].add(hesaplist.get(i).getAciklamaCikan());
            hesaptablo.insertRow(i, n[i]);
        }
        
        jTable1.setModel(hesaptablo);
        jTable1.repaint();
        
        hsp.rootPane.addComponentListener(new ComponentListener() {
            @Override
            
            public void componentResized(ComponentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void componentMoved(ComponentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void componentShown(ComponentEvent e) {
                System.out.println(a);
            }

            @Override
            public void componentHidden(ComponentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Bankalar b = new Bankalar();
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jFormattedTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField3ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, this.hesap_no_hesapDetay);
    }//GEN-LAST:event_formComponentShown

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(this, this.hesap_no_hesapDetay);
        List<codes.bankalar1> hesaplist = null;//new ArrayList<>();
        DefaultTableModel hesaptablo = (DefaultTableModel) jTable1.getModel();
        hesaptablo.getDataVector().clear();
        List<codes.bankalar1> hesapcikan = null;
        try {
            hesapcikan = new codes.bankalar1().hesapDetayCikan(this.hesap_no_hesapDetay);
        } catch (SQLException ex) {
            Logger.getLogger(hesapdetay.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            hesaplist = new codes.bankalar1().hesapDetayGiren(this.hesap_no_hesapDetay);
        } catch (SQLException ex) {
            Logger.getLogger(hesapdetay.class.getName()).log(Level.SEVERE, null, ex);
        }
        Vector[] v = new Vector[hesaplist.size()];
        int boyut =0;
        System.out.println(hesaplist.size());
        if(hesaplist.size()>=hesapcikan.size()){
            for(int n=0;n<hesaplist.size();n++){
            v[n] = new Vector();
            v[n].add(hesap_no_hesapDetay);
            String[] tarihgiren=hesaplist.get(n).getTarihGiren().split("/");
            if(hesapcikan.size()==0){
                v[n].add(hesaplist.get(n).getTarihGiren());
                v[n].add(hesaplist.get(n).getGirenMiktar());
                v[n].add("-");
                v[n].add(hesaplist.get(n).getAciklamaGiren());
            }else{
            for(int k=0;k<hesapcikan.size();k++){
                String[] tarihcikan = hesapcikan.get(k).getTarihCikan().split("/");
                System.out.println(tarihgiren[0]+"-"+tarihcikan[0]);
                if(Integer.parseInt(tarihgiren[2])>=Integer.parseInt(tarihcikan[2])){
                     if(Integer.parseInt(tarihgiren[1])>=Integer.parseInt(tarihcikan[1]))  {
                         if(Integer.parseInt(tarihgiren[0])>=Integer.parseInt(tarihcikan[0])){
                                v[n].add(hesaplist.get(n).getTarihGiren());
                                 v[n].add(hesaplist.get(n).getTarihGiren());
                                    v[n].add(hesaplist.get(n).getGirenMiktar());
                                    v[n].add("-");
                                    v[n].add(hesaplist.get(n).getAciklamaGiren());
                             } 
                         v[n].add(hesapcikan.get(k).getTarihCikan());
                         v[n].add(hesapcikan.get(k).getCikanMiktar());
                         v[n].add("-");
                         v[n].add(hesapcikan.get(k).getAciklamaCikan());
                       }
                     v[n].add(hesapcikan.get(k).getTarihCikan());
                     v[n].add(hesapcikan.get(k).getCikanMiktar());
                     v[n].add("-");
                     v[n].add(hesapcikan.get(k).getAciklamaCikan());
                }
            }
            
        }
            hesaptablo.insertRow(n, v[n]);
        }
           
   
        jTable1.setModel(hesaptablo);
         jTable1.repaint();
        } 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTextField1ComponentShown
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1ComponentShown

    private void jTable1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable1ComponentShown
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, this.hesap_no_hesapDetay);
    }//GEN-LAST:event_jTable1ComponentShown

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
          JOptionPane.showMessageDialog(this, jFormattedTextField1.getText());
        List<codes.bankalar1> hesaplist = null;//new ArrayList<>();
        DefaultTableModel hesaptablo = (DefaultTableModel) jTable1.getModel();
        hesaptablo.getDataVector().clear();
        List<codes.bankalar1> hesapcikan = new ArrayList<codes.bankalar1>();
        try {
            hesaplist = new codes.bankalar1().hesapDetayGirenTarihli(this.hesap_no_hesapDetay, jFormattedTextField1.getText(), jFormattedTextField3.getText());
        } catch (SQLException ex) {
            Logger.getLogger(hesapdetay.class.getName()).log(Level.SEVERE, null,"hataburada"+ ex);
            hesaplist=null;
        }
        try {
            hesapcikan = new codes.bankalar1().hesapDetayCikanTarihli(this.hesap_no_hesapDetay, jFormattedTextField1.getText(), jFormattedTextField3.getText());
        } catch (SQLException ex) {
            Logger.getLogger(hesapdetay.class.getName()).log(Level.SEVERE, null,"hatam= " +ex);
            hesapcikan=null;
        }
        
        Vector[] v = new Vector[hesaplist.size()];
        int boyut =0;
        System.out.println("hesaplist boyu="+hesaplist.size());
        if(hesaplist.size()>=hesapcikan.size()){
            for(int n=0;n<hesaplist.size();n++){
            v[n] = new Vector();
            v[n].add(hesap_no_hesapDetay);
            String[] tarihgiren=hesaplist.get(n).getTarihGiren().split("/");
            if(hesapcikan.size()==0){
                v[n].add(hesaplist.get(n).getTarihGiren());
                v[n].add(hesaplist.get(n).getGirenMiktar());
                v[n].add("-");
                v[n].add(hesaplist.get(n).getAciklamaGiren());
            }else{
            for(int k=0;k<hesapcikan.size();k++){
                String[] tarihcikan = hesapcikan.get(k).getTarihCikan().split("/");
                System.out.println(tarihgiren[0]+"-"+tarihcikan[0]);
                if(Integer.parseInt(tarihgiren[2])>=Integer.parseInt(tarihcikan[2])){
                     if(Integer.parseInt(tarihgiren[1])>=Integer.parseInt(tarihcikan[1]))  {
                         if(Integer.parseInt(tarihgiren[0])>=Integer.parseInt(tarihcikan[0])){
                                v[n].add(hesaplist.get(n).getTarihGiren());
                                 v[n].add(hesaplist.get(n).getTarihGiren());
                                    v[n].add(hesaplist.get(n).getGirenMiktar());
                                    v[n].add("-");
                                    v[n].add(hesaplist.get(n).getAciklamaGiren());
                             } 
                         v[n].add(hesapcikan.get(k).getTarihCikan());
                         v[n].add(hesapcikan.get(k).getCikanMiktar());
                         v[n].add("-");
                         v[n].add(hesapcikan.get(k).getAciklamaCikan());
                       }
                     v[n].add(hesapcikan.get(k).getTarihCikan());
                     v[n].add(hesapcikan.get(k).getCikanMiktar());
                     v[n].add("-");
                     v[n].add(hesapcikan.get(k).getAciklamaCikan());
                }
            }
            
        }
            hesaptablo.insertRow(n, v[n]);
        }
           
   
        jTable1.setModel(hesaptablo);
         jTable1.repaint();
        } 
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hesapdetay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hesapdetay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hesapdetay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hesapdetay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hesapdetay().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private java.awt.Scrollbar scrollbar1;
    // End of variables declaration//GEN-END:variables
}
