/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import codes.KasaListe;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.ScrollPane;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ozkan
 */
public class kasa extends javax.swing.JFrame {

    /**
     * Creates new form kasa
     */
    public kasa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel23 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jComboBox8 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setAutoscrolls(true);

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setAutoscrolls(true);
        jTabbedPane1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTabbedPane1ComponentShown(evt);
            }
        });

        jPanel1.setAutoscrolls(true);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "İşlem Türü Seçiniz", "Müşteriden Nakit Tahsilat", "Çek Girişi", "Senet Girişi", "Döviz Girişi", " ", " " }));
        jComboBox1.setToolTipText("İşlem Türü");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("İşlem Türü:");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        jLabel7.setText("jLabel7");

        jLabel8.setText("jLabel8");

        jLabel9.setText("Label9");

        jLabel10.setText("jLabel10");

        jTextField2.setText(" ");

        jTextField3.setText(" ");

        jTextField4.setText(" ");

        jTextField5.setText(" ");

        jTextField6.setText(" ");

        jTextField7.setText(" ");

        jTextField8.setText(" ");

        jTextField9.setText(" ");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jComboBox2ComponentShown(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel11.setText("Müşteri");

        jRadioButton1.setText("Banka Hesabı");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Nakit Kasa");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Kaydet");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Tümünü Görüntüle");

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        jLabel23.setText("Giriş Yeri");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TL", "DOLAR", "EURO" }));

        jLabel24.setText("Banka");

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "İşlem Türü", "Tutar", "Eklenme Tarihi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(406, 406, 406)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jFormattedTextField1)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(41, 41, 41)
                                .addComponent(jTextField6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1193, Short.MAX_VALUE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 1168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(41, 41, 41)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 1168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(41, 41, 41)
                                .addComponent(jTextField7)))
                        .addGap(68, 68, 68))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField9)
                            .addComponent(jTextField8)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel11)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRadioButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButton2))
                                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(54, 54, 54)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1043, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("GİRİŞ", jPanel1);

        jTextField11.setText(" ");

        jTextField12.setText(" ");

        jTextField13.setText(" ");

        jTextField14.setText(" ");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel22.setText("jLabel11");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "İşlem Türü Seçiniz", "Müşteriye Nakit Tahsilatı", "Çek Çıkışı", "Senet Çıkışı", "Döviz Çıkışı", " ", " " }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jRadioButton3.setText("Banka Hesabı");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jLabel12.setText("İşlem Türü:");

        jLabel13.setText("jLabel2");

        jRadioButton4.setText("Nakit Kasa");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jLabel14.setText("jLabel3");

        jLabel15.setText("jLabel4");

        jLabel16.setText("jLabel2");

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel25.setText("jLabel25");

        jFormattedTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField2ActionPerformed(evt);
            }
        });

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TL", "DOLAR", "EURO" }));

        jButton3.setText("Kaydet");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "İşlem Türü", "Tutar", "Eklenme Tarihi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jButton4.setText("Tümünü Görüntüle");

        jCheckBox1.setText("Kayıtlı Olmayan Çıkış");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(478, 478, 478)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel22)
                            .addComponent(jLabel25)
                            .addComponent(jLabel13))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton4))
                            .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 874, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jComboBox4, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.LEADING, 0, 435, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel16)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addGap(330, 330, 330)
                                .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 359, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jCheckBox1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jButton3)
                .addGap(28, 28, 28)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(822, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ÇIKIŞ", jPanel2);

        jScrollPane3.setViewportView(jTabbedPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1218, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    JComboBox comboSenet = new JComboBox();
    JComboBox comboBanka = new JComboBox();
    JComboBox combocek = new JComboBox();
     private String hesapNo;
      DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
     LocalDate localDate = LocalDate.now();
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedIndex()==1){
            //Nakit seçildiğinde
            
            /*codes.sirketler sirk = new codes.sirketler();
            List<codes.sirketler> sirklist=null;
            try {
                sirklist = sirk.sirketListesi();
            } catch (SQLException ex) {
                Logger.getLogger(kasa.class.getName()).log(Level.SEVERE, null, ex);
            }
            jComboBox2.removeAllItems();
            for(int i=0;i<sirklist.size();i++){
                jComboBox2.addItem(sirklist.get(i).getS_adi());
            }*/
            jComboBox2.repaint();
           jLabel24.setVisible(false);
            jComboBox6.setVisible(false);
            jLabel11.setText("Müşteri Adı:");
            jLabel2.setText("Tarih:");
            jLabel3.setText("Tutar:");
            jLabel4.setText("Açıklama:");
            jFormattedTextField1.setVisible(true);
            jTextField2.setVisible(true);
            jTextField3.setVisible(true);
            jTextField4.setVisible(false);
            jTextField5.setVisible(false);
            jTextField6.setVisible(false);
            jTextField7.setVisible(false);
            jTextField8.setVisible(false);
            jTextField9.setVisible(false);
            jLabel5.setVisible(false);
            jLabel6.setVisible(false);
            jLabel7.setVisible(false);
            jLabel8.setVisible(false);
            jLabel9.setVisible(false);
            jLabel10.setVisible(false);
            jRadioButton1.setEnabled(true);
            jRadioButton1.setSelected(false);
            jRadioButton2.setEnabled(true);
            jRadioButton2.setSelected(false);
            jPanel1.remove(this.comboBanka);
            jPanel1.remove(this.comboSenet);
        }
        else if(jComboBox1.getSelectedIndex()==2){
            //Çek Seçildiğinde
            jPanel1.remove(this.comboBanka);
            jPanel1.remove(this.comboSenet);
            jLabel24.setVisible(false);
            jComboBox6.setVisible(false);
            jRadioButton2.setSelected(true);
            jRadioButton1.setEnabled(false);
            jLabel11.setText("Müşteri Adı:");
            jLabel2.setText("Tarih:");
            jLabel3.setText("Tutar:");
            jLabel4.setText("Çek Numarası:");
            jLabel5.setText("Yazılma Tarihi:");
            jLabel6.setText("Vade Tarihi:");
            jLabel7.setText("Banka Adı:");
            jLabel8.setText("Çeki Yazan Kurumun Adı:");
            jLabel9.setText("Açıklama");
            jTextField4.setText(dtf.format(localDate));
            jTextField5.setText(dtf.format(localDate));
            
            jComboBox2.setVisible(true);
            jLabel4.setVisible(true);
            jLabel5.setVisible(true);
            jLabel6.setVisible(true);
            jLabel7.setVisible(true);
            jLabel8.setVisible(true);
            jLabel9.setVisible(true);
            jLabel10.setVisible(false);
            jTextField2.setVisible(true);
            jTextField3.setVisible(true);
            jTextField4.setVisible(true);
            jTextField5.setVisible(true);
            jTextField8.setVisible(true);
            jTextField7.setVisible(true);
            jTextField9.setVisible(false);
            jTextField6.setVisible(false);
            float x,y;
            x = jTextField6.getLocation().x;
            y = jTextField6.getLocation().y-20;
            //jComboBox6.setLocation(jTextField6.getLocation());
            
             comboBanka.setSize(300, 25);
             comboBanka.setName("Bankalar");
             //JFrame jp = new JFrame();
             //jp.add(combo);
                  ///BANKALARI COMBOBOX'a YAZDIRMA*/**////
            List<codes.bankalar1> bankalar =null;
            DefaultComboBoxModel comboListBanka = new DefaultComboBoxModel();
        try {
            bankalar = new codes.bankalar1().BankaListesi();
        } catch (SQLException ex) {
            Logger.getLogger(kasa.class.getName()).log(Level.SEVERE, null, ex);
        }
        for(int i=0;i<bankalar.size();i++){
            comboListBanka.addElement(bankalar.get(i).getBankalist_ad());
        }
        comboBanka.setModel(comboListBanka);
        comboBanka.repaint();
             jPanel1.add(comboBanka);
             comboBanka.setLocation(88, 360);
           
            
           
        }
        else if(jComboBox1.getSelectedIndex()==3){
            ////--------SENET SEÇİLİ-----------
            jPanel1.remove(this.comboBanka);
            jPanel1.remove(this.comboSenet);
            jLabel24.setVisible(false);
            jComboBox6.setVisible(false);
            jLabel2.setText("Tarih:");
            jLabel3.setText("Tutar:");
            jLabel4.setText("Senet No:");
            jLabel5.setText("Seneti Yazan Kurum Adı:");
            jRadioButton2.setSelected(true);
            //comboSenet.setSize(300, 25);
            //comboSenet.setName("Sirketler:");
            //jPanel1.add(comboSenet);
            //comboSenet.setLocation(jTextField4.getLocation().x, jTextField4.getLocation().y);
            jLabel6.setText("Vade:");
            jLabel7.setText("Senetin Yazılma Tarihi:");
            jLabel8.setText("Açıklama:");
            jLabel2.setVisible(true);
            jLabel3.setVisible(true);
            jLabel4.setVisible(true);
            jLabel5.setVisible(true);
            jLabel6.setVisible(true);
            jLabel7.setVisible(true);
            jLabel8.setVisible(true);
            jLabel9.setVisible(false);
            jLabel10.setVisible(false);
            jFormattedTextField1.setVisible(true);
            jTextField2.setVisible(true);
            jTextField3.setVisible(true);
            jTextField4.setVisible(true);
            jTextField5.setVisible(true);
            jTextField6.setVisible(true);
            jTextField7.setVisible(true);
            jTextField8.setVisible(false);
            jTextField9.setVisible(false);
            jRadioButton1.setEnabled(false);
            jPanel1.remove(this.comboBanka);
        }
        else if(jComboBox1.getSelectedIndex()==4){
            /////-------DÖVİZ SEÇİLİ------
            jComboBox5.setSelectedIndex(2);
            jLabel11.setVisible(true);
            jComboBox2.setVisible(true);
            jLabel2.setVisible(true);
            jFormattedTextField1.setVisible(true);
            jLabel3.setVisible(true);
            jLabel4.setVisible(true);
            jLabel5.setVisible(true);
            jLabel6.setVisible(false);
            jLabel7.setVisible(false);
            jLabel8.setVisible(false);
            jLabel9.setVisible(false);
            jLabel10.setVisible(false);
            jTextField3.setVisible(true);
            jTextField2.setVisible(true);
            jTextField4.setVisible(true);
            jTextField5.setVisible(false);
            jTextField6.setVisible(false);
            jTextField7.setVisible(false);
            jTextField8.setVisible(false);
            jTextField9.setVisible(false);
            jRadioButton1.setEnabled(true);
            jRadioButton2.setEnabled(true);
            jLabel2.setText("Tarih:");
            jLabel3.setText("Tutar:");
            jLabel4.setText("Anlık Kur:");
            jLabel11.setText("Müşteri Adı:");
            jLabel5.setText("Açıklama:");
            jPanel1.remove(this.comboBanka);
            jPanel1.remove(this.comboSenet);
            
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedIndex()==1 && jRadioButton1.isSelected()==true) 
        //---------------Banka hesabına ekleme--------------
        {
             this.hesapNo = jComboBox6.getSelectedItem().toString().trim();
         String[] dizi = this.hesapNo.split(" - ");
         this.hesapNo = dizi[0];
        boolean durum = false;
        codes.KasaGiris kg = new codes.KasaGiris();
        codes.sirketler sk = new codes.sirketler();
        String kurum = null;
            try {
                kurum = sk.sicilAl(jComboBox2.getSelectedItem().toString());
            } catch (SQLException ex) {
               // Logger.getLogger(kasa.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        kg.setBanka_kurum_no(kurum);
        kg.setBanka_giren_miktar(Float.parseFloat(jTextField2.getText().trim()));
        //kg.setBanka_tarih(tarih[2]+"/"+tarih[1]+"/"+tarih[0]);
        kg.setBanka_tarih(jFormattedTextField1.getText().trim());
        kg.setHesap_no(this.hesapNo);
        kg.setBanka_aciklama(jTextField3.getText().trim());
        try {
            durum = kg.NakitHesabaEkle(kg);
            if(durum){
            JOptionPane.showMessageDialog(this, "Başarılı");
            jComboBox2.setSelectedIndex(0);
            jComboBox6.setSelectedIndex(0);
            jTextField2.setText("");
            jTextField3.setText("");
            jFormattedTextField1.setText(dtf.format(localDate));
            this.hesapNo=null;
            }else{
                JOptionPane.showMessageDialog(this, "Hata");
            }
           
       } catch (SQLException ex) {
           // Logger.getLogger(kasa.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex.getMessage());
        }
        }
        else if (jComboBox1.getSelectedIndex()==1 && jRadioButton2.isSelected()==true && jRadioButton1.isSelected()==false)
        //-----------Nakit ekleme--------------
        {
        boolean durum = false;
        codes.KasaGiris kg = new codes.KasaGiris();
        codes.sirketler sk = new codes.sirketler();
        String kurum = null;
            try {
                kurum = sk.sicilAl(jComboBox2.getSelectedItem().toString().trim());
            } catch (SQLException ex) {
                Logger.getLogger(kasa.class.getName()).log(Level.SEVERE, null, ex);
            }
        kg.setKurum_no(kurum);
        kg.setTutar_nakit(Float.parseFloat(jTextField2.getText().trim()));
        kg.setGiris_tarih(jFormattedTextField1.getText().trim());
        kg.setAciklama(jTextField3.getText().trim());
        
        try {
            durum = kg.NakitEkle(kg);
            if(durum){
                JOptionPane.showMessageDialog(this, "Başarılı");
            jTextField2.setText("");
            jFormattedTextField1.setText(dtf.format(localDate));
            jTextField3.setText("");
            jComboBox5.setSelectedItem("TL");
            }
            
       } catch (SQLException ex) {
            Logger.getLogger(kasa.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Hata:"+ex);
        }
        }
        else if(jComboBox1.getSelectedIndex()==3 && jRadioButton2.isSelected()==true && jRadioButton1.isSelected()==false){
        //-----------------Senet ekle -------------------s   
        
         boolean durum = false;
        codes.KasaGiris kg = new codes.KasaGiris();
        codes.sirketler sk = new codes.sirketler();
        String kurumno=null;
            try {
                kurumno = sk.sicilAl(jComboBox2.getSelectedItem().toString().trim());
            } catch (SQLException ex) {
                Logger.getLogger(kasa.class.getName()).log(Level.SEVERE, null, ex);
            }
        kg.setSenet_no(jTextField3.getText().trim());
        kg.setSenet_yazan_kurum_no(jTextField4.getText().trim().trim());
        kg.setSenet_vade(jTextField5.getText().trim());
        kg.setSenet_tutar(Float.parseFloat(jTextField2.getText().trim()));
        kg.setSenet_yazilma_tarih(jTextField6.getText().trim());
        //kg.setSenet_kurum_no(jComboBox2.getSelectedItem().toString());
        kg.setSenet_kurum_no(kurumno);
        kg.setSenet_giris_tarihi(jFormattedTextField1.getText().trim());
        kg.setSenet_aciklama(jTextField7.getText().trim().trim());
        try {
            durum = kg.SenetEkle(kg);
            if(durum){
                JOptionPane.showMessageDialog(this, "Başarılı");
            jTextField2.setText("");
            jFormattedTextField1.setText(dtf.format(localDate));
            jTextField3.setText("");
            jComboBox5.setSelectedItem("TL");
            jTextField6.setText("");
            jTextField5.setText("");
            jTextField4.setText(""); 
            jTextField7.setText("");
            }
           
       } catch (SQLException ex) {
            Logger.getLogger(kasa.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "hata: "+ex);
        }
    }
        else if(jComboBox1.getSelectedIndex()==2 && jRadioButton2.isSelected()==true && jRadioButton1.isSelected()==false){
        //////////////////-----Çek Ekle------///////////////
            boolean durum = false;
        codes.KasaGiris kg = new codes.KasaGiris();
        codes.sirketler sk = new codes.sirketler();
        String kurum = null;
            try {
                kurum = sk.sicilAl(jComboBox2.getSelectedItem().toString().trim());
            } catch (SQLException ex) {
                Logger.getLogger(kasa.class.getName()).log(Level.SEVERE, null, ex);
            }
        kg.setCek_kurum_no(kurum);
        kg.setCek_tutar(Float.parseFloat(jTextField2.getText().trim()));
        kg.setCek_gelis_tarihi(jFormattedTextField1.getText().trim());
        kg.setCek_no(jTextField3.getText().trim());
        kg.setCek_yazilma_tarihi(jTextField4.getText().trim());
        kg.setCek_vade(jTextField5.getText().trim());
        kg.setCek_yazan_kurum_no(jTextField7.getText().trim());
        kg.setCek_aciklama(jTextField8.getText().trim());
        //kg.setCek_banka_no(comboBanka.getSelectedItem().toString());
        codes.bankalar1 bn = new codes.bankalar1();
        int bankanu =0; 
            try {
                 bankanu = bn.bankaNoBul(comboBanka.getSelectedItem().toString().trim());
            } catch (SQLException ex) {
                Logger.getLogger(kasa.class.getName()).log(Level.SEVERE, null, ex);
            }
        kg.setCek_banka_no(String.valueOf(bankanu));
            try {
                durum = kg.CekEkle(kg);
                if(durum){
                    JOptionPane.showMessageDialog(this, "Başarılı");
                jTextField2.setText("");
                jFormattedTextField1.setText(dtf.format(localDate));
                jTextField3.setText("");
                jTextField4.setText("");
                jTextField5.setText("");
                jTextField7.setText("");
                comboBanka.setSelectedIndex(1);
                jTextField4.setText(dtf.format(localDate));
                jTextField5.setText(dtf.format(localDate));
                
                }
                    
                
            } catch (SQLException ex) {
                Logger.getLogger(kasa.class.getName()).log(Level.SEVERE, null, ex);
                 JOptionPane.showMessageDialog(this, "Hata Oluştu./n Kodu:"+ex);
            }
            
        }
        else if(jComboBox1.getSelectedIndex()==4 && jRadioButton2.isSelected()==true && jRadioButton1.isSelected()==false){
           ///////////////----------DÖVİZ EKLE-------/////////////
            boolean durum = false;
            codes.KasaGiris kg = new codes.KasaGiris();
            codes.sirketler sk = new codes.sirketler();
        String kurum = null;
            try {
                kurum = sk.sicilAl(jComboBox2.getSelectedItem().toString().trim());
            } catch (SQLException ex) {
                Logger.getLogger(kasa.class.getName()).log(Level.SEVERE, null, ex);
            }
            kg.setDoviz_tarih(jFormattedTextField1.getText().trim());
            kg.setDoviz_giren_tutar(Float.parseFloat(jTextField2.getText().trim()));
            kg.setDoviz_adi(jComboBox5.getSelectedItem().toString().trim());
            kg.setDoviz_kur(Float.valueOf(jTextField3.getText().trim()));
            kg.setDoviz_kurum_no(kurum);
            kg.setDoviz_aciklama(jTextField4.getText().trim());
            try {
                durum=kg.DovizEkle(kg);
                if(durum){
                    JOptionPane.showMessageDialog(this, "Başarılı");
                jTextField2.setText("");
                jFormattedTextField1.setText(dtf.format(localDate));
                jTextField3.setText("");
                jTextField4.setText("");
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(kasa.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Hata Oluştu./n Kodu:"+ex);
            }
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
         jLabel24.setText("Hesap No:");
            jLabel24.setVisible(true);
            jComboBox6.setVisible(true);
            jRadioButton2.setSelected(false);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        jRadioButton1.setSelected(false);
        jLabel24.setVisible(false);
            jComboBox6.setVisible(false);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jTabbedPane1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTabbedPane1ComponentShown
       
       
    }//GEN-LAST:event_jTabbedPane1ComponentShown

    private void jComboBox2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jComboBox2ComponentShown
        // TODO add your handling code here:
         
            // TODO add your handling code here:
        
      
    }//GEN-LAST:event_jComboBox2ComponentShown

    public void kasaAcilis(){
         jTextField6.setVisible(false); 
       jTextField5.setVisible(false);
       jTextField7.setVisible(false);
       jTextField8.setVisible(false);
       jTextField9.setVisible(false);
       jLabel6.setVisible(false);
       jLabel7.setVisible(false);
       jLabel8.setVisible(false);
       jLabel9.setVisible(false);
       jLabel10.setVisible(false);
       jTextField1.setEnabled(false);
        jFormattedTextField1.setText(dtf.format(localDate));
        jFormattedTextField2.setText(dtf.format(localDate));
        
       this.hesapNo = null;
            List<codes.sirketler> sirketlist = null;//new ArrayList<>();
            DefaultComboBoxModel comboBoxModel = new DefaultComboBoxModel();
        try {
            sirketlist = new codes.sirketler().sirketListesi();
        } catch (SQLException ex) {
            Logger.getLogger(kasa.class.getName()).log(Level.SEVERE, null, ex);
        }
            ArrayList<String> listem = new ArrayList();
            for(int n=0;n<sirketlist.size();n++){
                //jComboBox2.addItem(sirketlist.get(n).getS_adi());
                 //comboBoxModel.addElement(sirketlist.get(n).getS_adi());
                 listem.add(sirketlist.get(n).getS_adi());
            }
            for(int i=0;i<listem.size();i++){
                comboBoxModel.addElement(listem.get(i));
            }
            jComboBox2.setModel(comboBoxModel);
            jComboBox2.repaint();
            
            jComboBox4.setModel(comboBoxModel);
            jComboBox4.repaint();
        
             /////-----BANKA HESAPLARININ COMBOBOX2'YE AKTARILMASI-----
         
         List<codes.hesaplar> hesaplist = null;//new ArrayList<>();
        DefaultComboBoxModel combomodel = new DefaultComboBoxModel();
        
        try {
            hesaplist = new codes.hesaplar().HesaplarListesi();
        } catch (SQLException ex) {
            Logger.getLogger(kasa.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        for(int n=0;n<hesaplist.size();n++){
            
            String hesapno = hesaplist.get(n).getHesap_no();
            String bankaadi = null;
            try {
                bankaadi = new codes.bankalar1().bankaAdiBul(Integer.parseInt(hesaplist.get(n).getBanka_no()));
            } catch (SQLException ex) {
                Logger.getLogger(kasa.class.getName()).log(Level.SEVERE, null, ex);
            }
            String sube = hesaplist.get(n).getHesap_no();
            String sonuc = hesapno+" - "+sube+" - "+bankaadi;
            combomodel.addElement(sonuc);
        }
        jComboBox6.setModel(combomodel);
        jComboBox6.repaint();
        jComboBox7.setModel(combomodel);
        jComboBox7.repaint();
        //////////////////SON 20 İŞLEM Giriş///////////////////
        List<codes.KasaListe> kasalist = new ArrayList<>();
        DefaultTableModel tablemodel = (DefaultTableModel) jTable3.getModel();
        tablemodel.getDataVector().clear();
      
        try {
            kasalist = new codes.KasaListe().Sonislemler();
        } catch (SQLException ex) {
            Logger.getLogger(kasa.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Vector[] v = new Vector[kasalist.size()];
        for(int n=0;n<kasalist.size();n++){
            v[n] = new Vector();
            v[n].add(kasalist.get(n).getSonListAd());
            v[n].add(kasalist.get(n).getSonListTutar());
            v[n].add(kasalist.get(n).getSonListtarih());
            tablemodel.insertRow(n, v[n]);
        }
        jTable3.setModel(tablemodel);
        jTable3.repaint();
        
        /////////////////////////////
        
        //////////SENET COMBOBOX///////////////
              comboSenet.setSize(300, 25);
             comboSenet.setName("Senetler");
            List<codes.senetler> senetler =null;
            DefaultComboBoxModel comboListSenet = new DefaultComboBoxModel();
        
             try {
                 senetler = new codes.senetler().senet_elde();
             } catch (Throwable ex) {
                 Logger.getLogger(kasa.class.getName()).log(Level.SEVERE, null, ex);
             }
       
        for(int i=0;i<senetler.size();i++){
            comboListSenet.addElement(senetler.get(i).getSenet_no());
        }
             comboSenet.setModel(comboListSenet);
             comboSenet.repaint();
             //jPanel2.add(comboBanka);
             comboSenet.setLocation(121, 180);
             
             ///////////////ÇEK COMBOBOX/////////
             
                 List<codes.cekler> cekler =null;
             DefaultComboBoxModel comboListCek = new DefaultComboBoxModel();
             try {
                 cekler = new codes.cekler().cek_elde();
             } catch (SQLException ex) {
                 Logger.getLogger(kasa.class.getName()).log(Level.SEVERE, null, ex);
             }
             for(int i=0;i<cekler.size();i++){
                 comboListCek.addElement(cekler.get(i).getCekno());
             }
             combocek.setModel(comboListCek);
             combocek.setSize(300,25);
             combocek.setName("Cekler");
             combocek.setLocation(121, 180);
             combocek.setAlignmentY((float) 0.5);
             combocek.repaint();
             
             
             sonCikislar();
    }
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
       /* JPanel jp = new JPanel();
        jp.add(jTabbedPane1);
       JScrollPane scroll = new JScrollPane(jp);
        JScrollPane s = new JScrollPane(jp, JScrollPane.VERTICAL_SCROLLBAR_NEVER, JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);*/
      kasaAcilis();
         
    }//GEN-LAST:event_formComponentShown
    private void sonCikislar(){
    List<codes.KasaListe> kasalist = new ArrayList<>();
        DefaultTableModel tablemodel = (DefaultTableModel) jTable2.getModel();
        tablemodel.getDataVector().clear();
        tablemodel.setRowCount(0);
        try {
            kasalist = new codes.KasaListe().SonislemlerCikis();
        } catch (SQLException ex) {
            Logger.getLogger(kasa.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Vector[] v = new Vector[kasalist.size()];
        for(int n=0;n<kasalist.size();n++){
            v[n] = new Vector();
            v[n].add(kasalist.get(n).getSonListAd());
            v[n].add(kasalist.get(n).getSonListTutar());
            v[n].add(kasalist.get(n).getSonListtarih());
            tablemodel.insertRow(n, v[n]);
        }
        jTable2.setModel(tablemodel);
        jTable2.repaint();
    }
    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
        this.hesapNo = jComboBox6.getSelectedItem().toString();
         String[] dizi = this.hesapNo.split(" - ");
         this.hesapNo = dizi[0];
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
         if(jComboBox3.getSelectedIndex()==1){
            //Nakit seçildiğinde
            
            jPanel2.remove(this.comboBanka);
            jPanel2.remove(this.comboSenet);
            jPanel2.remove(this.combocek);
            jTextField11.setVisible(true);
            
            jComboBox4.repaint();
            jComboBox4.setVisible(true);
            jLabel24.setVisible(false);
            jComboBox6.setVisible(false);
            jComboBox7.setVisible(false);
            jLabel22.setText("Müşteri Adı:");
            jLabel13.setText("Tarih:");
            jLabel14.setText("Tutar:");
            jLabel14.setVisible(true);
            jLabel15.setVisible(true);
            jLabel15.setText("Açıklama:");
            jFormattedTextField1.setVisible(true);
            jTextField12.setVisible(true);
            jTextField13.setVisible(false);
            jTextField14.setVisible(false);
     
            jLabel16.setVisible(false);
         
            jRadioButton3.setEnabled(true);
            jRadioButton3.setSelected(false);
            jRadioButton4.setEnabled(true);
            jRadioButton4.setSelected(false);
            
        }
        else if(jComboBox3.getSelectedIndex()==2){
            //Çek Seçildiğinde
            jPanel2.remove(this.comboSenet);
            jPanel2.remove(this.comboBanka);
            int l14x = jLabel14.getLocation().x;
            int l14y = jLabel14.getLocation().y;
             System.out.println(l14x+"-"+l14y);
            jPanel2.remove(this.comboBanka);
            jPanel2.remove(this.comboSenet);
            jLabel25.setVisible(false);
            jComboBox7.setVisible(false);
            jRadioButton4.setSelected(true);
            jRadioButton3.setEnabled(false);
            jLabel22.setText("Müşteri Adı:");
            jLabel13.setText("Tarih:");
            jLabel13.setVisible(true);
            jLabel14.setVisible(true);
            jFormattedTextField2.setVisible(true);
            jComboBox8.setVisible(false);
            jLabel14.setText("Çek Numarası:");
            jLabel16.setText("Banka Adı:");
            jLabel15.setText("Açıklama:");
            jComboBox4.setVisible(true);
            jLabel15.setVisible(true);
            jLabel16.setVisible(false);
      
            jLabel14.setVisible(true);
            jLabel13.setLocation(0, 113);
            jTextField11.setVisible(false);
            jTextField12.setVisible(true);
            jTextField13.setVisible(false);
            jTextField14.setVisible(true);
            int x,y;
            x = jTextField11.getLocation().x;
            y = jTextField11.getLocation().y;
            //jComboBox6.setLocation(jTextField6.getLocation());
            
             comboBanka.setSize(300, 25);
             comboBanka.setName("Bankalar");
             //JFrame jp = new JFrame();
             //jp.add(combo);
                  ///BANKALARI COMBOBOX'a YAZDIRMA*/**////
            List<codes.bankalar1> bankalar =null;
            DefaultComboBoxModel comboListBanka = new DefaultComboBoxModel();
        try {
            bankalar = new codes.bankalar1().BankaListesi();
        } catch (SQLException ex) {
            Logger.getLogger(kasa.class.getName()).log(Level.SEVERE, null, ex);
        }
        for(int i=0;i<bankalar.size();i++){
            comboListBanka.addElement(bankalar.get(i).getBankalist_ad());
        }
             comboBanka.setModel(comboListBanka);
             comboBanka.repaint();
             //jPanel2.add(comboBanka);
             comboBanka.setLocation(135, 247);
         
             combocek.setVisible(true);
             
             jPanel2.add(combocek);
            
             
            
            jTextField11.setVisible(false);
            //jTextField7.setVisible(true);
            jTextField13.setVisible(false);
            jTextField14.setVisible(false);
          
        }
        else if(jComboBox3.getSelectedIndex()==3){
            ////--------SENET SEÇİLİ-----------
            jPanel2.remove(this.comboBanka);
            jPanel2.remove(this.comboSenet);
            jPanel2.remove(this.combocek);
            comboBanka.setVisible(false);
            combocek.setVisible(false);
            comboSenet.setVisible(false);
            jLabel24.setVisible(false);
            jComboBox6.setVisible(false);
            jLabel13.setText("Tarih:");
            jLabel14.setText("Senet No:");
            jLabel15.setText("Açıklama:");
            jRadioButton4.setSelected(true);
            jRadioButton3.setEnabled(false);
            jComboBox7.setVisible(false);
            jLabel25.setVisible(false);
            //comboSenet.setSize(300, 25);
            //comboSenet.setName("Sirketler:");
            //jPanel1.add(comboSenet);
            //comboSenet.setLocation(jTextField4.getLocation().x, jTextField4.getLocation().y);
            jLabel13.setVisible(true);
            jComboBox8.setVisible(false);
            jLabel14.setVisible(true);
            jLabel15.setVisible(true);
            jLabel16.setVisible(false);
         
            jFormattedTextField1.setVisible(true);
            jTextField12.setVisible(true);
            jTextField13.setVisible(false);
            jTextField14.setVisible(false);
        
            jTextField11.setVisible(false);
            jRadioButton3.setEnabled(false);
            jPanel2.remove(this.comboBanka);
            
         
            //jComboBox6.setLocation(jTextField6.getLocation());
            
       
             comboSenet.setVisible(true);
             jPanel2.add(comboSenet);
            
        }
        else if(jComboBox3.getSelectedIndex()==4){
            /////-------DÖVİZ SEÇİLİ------
             jPanel2.remove(this.comboBanka);
            jPanel2.remove(this.comboSenet);
            jPanel2.remove(this.comboSenet);
            comboBanka.setVisible(false);
            combocek.setVisible(false);
            comboSenet.setVisible(false);
            jComboBox7.setVisible(false);
            jComboBox5.setSelectedIndex(1);
            jComboBox8.setVisible(true);
            jComboBox8.setSelectedIndex(1);
            jLabel22.setVisible(true);
            jComboBox2.setVisible(true);
            jLabel2.setVisible(true);
            jLabel25.setVisible(false);
            jFormattedTextField2.setVisible(true);
            jLabel13.setVisible(true);
            jLabel14.setVisible(true);
            jLabel15.setVisible(true);
            jLabel16.setVisible(true);
          
            jTextField11.setVisible(true);
            jTextField12.setVisible(true);
            jTextField13.setVisible(true);
            jTextField14.setVisible(false);
           
            
            jRadioButton3.setEnabled(false);
            jRadioButton4.setEnabled(false);
            jRadioButton4.setSelected(true);
            jLabel13.setText("Tarih:");
            jLabel14.setText("Tutar:");
            jLabel15.setText("Anlık Kur:");
            jLabel22.setText("Müşteri Adı:");
            jLabel16.setText("Açıklama:");
        }
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         if(jComboBox3.getSelectedIndex()==1 && jRadioButton3.isSelected()==true && jRadioButton4.isSelected()==false) 
        //---------------Banka hesabından Çıkış--------------
        {
         String hesapNo1 = jComboBox7.getSelectedItem().toString().trim();
         String[] dizi = hesapNo1.split(" - ");
         hesapNo1 = dizi[0];
        boolean durum = false;
        codes.KasaCikis kc = new codes.KasaCikis();
        codes.sirketler sk = new codes.sirketler();
        String kurum = null;
            try {
                kurum = sk.sicilAl(jComboBox4.getSelectedItem().toString().trim());
            } catch (SQLException ex) {
                Logger.getLogger(kasa.class.getName()).log(Level.SEVERE, null, ex);
            }
        if(jCheckBox1.isSelected() && !jTextField1.getText().equals("")){
            kc.setBanka_kurum_no(jTextField1.getText().trim());
        }else{
            kc.setBanka_kurum_no(kurum);
        }    
        
        kc.setBanka_cikan_miktar(Float.parseFloat(jTextField11.getText().trim()));
        kc.setBanka_tarih(jFormattedTextField2.getText().trim());
        kc.setHesap_no(hesapNo1);
        kc.setBanka_aciklama(jTextField12.getText().trim());
        try {
            durum = kc.NakitHesaptanCikis(kc);
            if(durum){
                JOptionPane.showMessageDialog(this, "Başarılı");
            jComboBox3.setSelectedIndex(0);
            jComboBox4.setSelectedIndex(0);
            jTextField11.setText("");
            jTextField2.setText("");
            jFormattedTextField2.setText(dtf.format(localDate));
            jTextField1.setText("");
            this.hesapNo=null;
            }else{
                JOptionPane.showMessageDialog(this, "Hata gerçekleşti. Kaydedilemedi");
                this.hesapNo=null;
            }
            
       } catch (SQLException ex) {
            Logger.getLogger(kasa.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
         else if(jComboBox3.getSelectedIndex()==1 && jRadioButton4.isSelected()==true && jRadioButton3.isSelected()==false)
        //-----------Nakit Çıkış--------------
        {
        boolean durum = false;
        codes.KasaCikis kc = new codes.KasaCikis();
        codes.sirketler sk = new codes.sirketler();
        String kurum = null;
            try {
                kurum = sk.sicilAl(jComboBox4.getSelectedItem().toString().trim());
            } catch (SQLException ex) {
                Logger.getLogger(kasa.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(jCheckBox1.isSelected() && !jTextField1.getText().equals("")){
            kc.setKurum_no(jTextField1.getText().trim());
        }else{
            kc.setKurum_no(kurum);
        } 
        kc.setTutar_nakit(Float.parseFloat(jTextField11.getText().trim()));
        kc.setCikis_tarih(jFormattedTextField2.getText().trim());
        kc.setAciklama(jTextField12.getText().trim());
        
        try {
            durum = kc.NakitCikis(kc);
            if(durum){
            JOptionPane.showMessageDialog(this, "Başarılı");
            jTextField12.setText("");
            jFormattedTextField2.setText(dtf.format(localDate));
            jTextField11.setText("");
            jComboBox8.setSelectedItem("TL");
            jComboBox4.setSelectedIndex(0);
            jTextField1.setText("");
            }else{
                JOptionPane.showMessageDialog(this, "Hata Gerçekleşti. Kaydedilemedi");
            }
            
       } catch (SQLException ex) {
            Logger.getLogger(kasa.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Hata:"+ex);
            }
       }
       else if(jComboBox3.getSelectedIndex()==3 && jRadioButton4.isSelected()==true && jRadioButton3.isSelected()==false){
        //-----------------Senet Çıkış -------------------s   
        
        boolean durum = false;
        codes.KasaCikis kcs = new codes.KasaCikis();
        codes.sirketler sk = new codes.sirketler();
        String kurumno=null;
            try {
                kurumno = sk.sicilAl(jComboBox4.getSelectedItem().toString().trim());
            } catch (SQLException ex) {
                Logger.getLogger(kasa.class.getName()).log(Level.SEVERE, null, ex);
            }
        kcs.setSenet_no(comboSenet.getSelectedItem().toString().trim());
        String senetNo1 = comboSenet.getSelectedItem().toString().trim();
         if(jCheckBox1.isSelected() && !jTextField1.getText().equals("")){
            kcs.setSenet_kurum_no(jTextField1.getText().trim());
        }else{
            kcs.setSenet_kurum_no(kurumno);
        } 
        
        kcs.setSenet_cikis_tarihi(jFormattedTextField2.getText().trim());
        kcs.setSenet_aciklama(jTextField12.getText().trim());
        boolean durum2 = false;
        try {
            durum = kcs.SenetCikis(kcs);
            durum2 = kcs.SenetCikisGuncelle(senetNo1);
            if(durum && durum2){
            JOptionPane.showMessageDialog(this, "Başarılı");
            jComboBox4.setSelectedIndex(0);
            jFormattedTextField2.setText(dtf.format(localDate));
            comboSenet.setSelectedIndex(0);
            jComboBox8.setSelectedItem("TL");
            jTextField12.setText("");
            jTextField1.setText("");
            }else{
                JOptionPane.showMessageDialog(this, "Hata Gerçekleşti. Kaydedilemedi");
            }
            
       } catch (SQLException ex) {
            Logger.getLogger(kasa.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "hata: "+ex);
        }
    }
         
         else if(jComboBox3.getSelectedIndex()==2 && jRadioButton4.isSelected()==true && jRadioButton3.isSelected()==false){
        //////////////////-----Çek Çıkış------///////////////
        boolean durum = false;
        codes.KasaCikis kcc = new codes.KasaCikis();
        codes.sirketler sk = new codes.sirketler();
        
        String kurumno=null;
            try {
                kurumno = sk.sicilAl(jComboBox4.getSelectedItem().toString().trim());
            } catch (SQLException ex) {
                Logger.getLogger(kasa.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(jCheckBox1.isSelected() && !jTextField1.getText().equals("")){
            kcc.setCek_kurum_no(jTextField1.getText().trim());
        }else{
            kcc.setCek_kurum_no(kurumno);
        } 
        kcc.setCek_cikis_tarihi(jFormattedTextField2.getText().trim());
        kcc.setCek_no(combocek.getSelectedItem().toString().trim());
        kcc.setCek_aciklama(jTextField12.getText().trim());
        String cekNo1 = combocek.getSelectedItem().toString().trim();
        codes.bankalar1 bn = new codes.bankalar1();
            try {
                 Boolean durum2 = false;
                codes.KasaCikis kc = new codes.KasaCikis();
                durum = kcc.CekCikis(kcc);
                if(durum){
                     durum2 = kc.CekCikisGuncelle(cekNo1);
                JOptionPane.showMessageDialog(this, "Başarılı");
                jComboBox4.setSelectedIndex(0);
                jFormattedTextField2.setText(dtf.format(localDate));
                jTextField3.setText("");
                jTextField4.setText("");
                jTextField5.setText("");
                jTextField7.setText("");
                jTextField12.setText("");
                jTextField1.setText("");
                combocek.setSelectedIndex(0);
                }else{
                     JOptionPane.showMessageDialog(this, "Hata Gerçekleşti. Kaydedilemedi");
                }
            } catch (SQLException ex) {
                Logger.getLogger(kasa.class.getName()).log(Level.SEVERE, null, ex);
                 JOptionPane.showMessageDialog(this, "Hata Oluştu./n Kodu:"+ex);
            }
            
            
        }
        else if(jComboBox3.getSelectedIndex()==4 && jRadioButton4.isSelected()==true && jRadioButton3.isSelected()==false){
           ///////////////----------DÖVİZ ÇIKIŞ-------/////////////
            boolean durum = false;
            codes.KasaCikis kcd = new codes.KasaCikis();
            kcd.setDoviz_tarih(jFormattedTextField2.getText().trim());
            kcd.setDoviz_cikan_tutar(Float.parseFloat(jTextField11.getText().trim()));
            kcd.setDoviz_adi(jComboBox8.getSelectedItem().toString().trim());
            kcd.setDoviz_kur(Float.valueOf(jTextField12.getText().trim()));
            kcd.setDoviz_aciklama(jTextField13.getText().trim());
            codes.sirketler sk = new codes.sirketler();
        String kurumno=null;
            try {
                kurumno = sk.sicilAl(jComboBox4.getSelectedItem().toString());
            } catch (SQLException ex) {
                Logger.getLogger(kasa.class.getName()).log(Level.SEVERE, null, ex);
            }
             if(jCheckBox1.isSelected() && !jTextField1.getText().equals("")){
            kcd.setDoviz_kurum_no(jTextField1.getText().trim());
        }else{
            kcd.setDoviz_kurum_no(kurumno);
        } 
            
            try {
                durum=kcd.DovizCikis(kcd);
                if(durum){
                     JOptionPane.showMessageDialog(this, "Başarılı");
                jTextField11.setText("");
                jFormattedTextField2.setText(dtf.format(localDate));
                jTextField12.setText("");
                jTextField13.setText("");
                jTextField1.setText("");
                }else{
                    JOptionPane.showMessageDialog(this, "Hata Gerçekleşti. Kaydedilemedi");
                }
               
            } catch (SQLException ex) {
                Logger.getLogger(kasa.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Hata Oluştu./n Kodu:"+ex);
            }
        }
         
         
         
             
         
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        jRadioButton4.setSelected(false);
        jComboBox7.setVisible(true);
        jLabel25.setVisible(true);
        jLabel25.setText("Banka Hesabı:");
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        jRadioButton3.setSelected(false);
        jComboBox7.setVisible(false);
        jLabel25.setVisible(false);
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jFormattedTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected()){
            jTextField1.setEnabled(true);
            jComboBox4.setEnabled(false);
        }
        else
            jTextField1.setEnabled(false);
            jComboBox4.setEnabled(true);
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kasa().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
