/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;


import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Fadime
 */
public class senetler extends javax.swing.JFrame {

    /**
     * Creates new form senetler
     */
    public senetler() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        giden = new javax.swing.JRadioButton();
        hepsi = new javax.swing.JRadioButton();
        elde = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        giden.setText("Giden Senetler");
        giden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gidenActionPerformed(evt);
            }
        });

        hepsi.setText("Hepsini Gör");
        hepsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hepsiActionPerformed(evt);
            }
        });

        elde.setText("Eldeki Senetler");
        elde.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eldeMouseClicked(evt);
            }
        });
        elde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eldeActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Senet No", "Şirket", "Tutar", "Vade Tarihi", "Geliş Tarihi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField1.setText("Tüm Senetler");
        jTextField1.setDisabledTextColor(new java.awt.Color(10, 9, 7));
        jTextField1.setEnabled(false);

        jButton1.setText("İşlem Yap");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(elde)
                                .addGap(32, 32, 32)
                                .addComponent(giden))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36)
                        .addComponent(hepsi)))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(elde)
                    .addComponent(giden)
                    .addComponent(hepsi))
                .addGap(34, 34, 34)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eldeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eldeActionPerformed
        // TODO add your handling code here:
        hepsi.setSelected(false);
        giden.setSelected(false);
        
            DefaultTableModel sir_tablo = (DefaultTableModel) jTable1.getModel();
            sir_tablo.getDataVector().clear();
            sir_tablo.setRowCount(0);
            List<codes.senetler> senetlisteleme = null;//new ArrayList<>();

            try {
                senetlisteleme=new codes.senetler().senet_elde();
            } catch (SQLException ex) {
                Logger.getLogger(senetler.class.getName()).log(Level.SEVERE, null, ex);
            }
                 
            Vector[] v = new Vector[senetlisteleme.size()];
            System.out.println(senetlisteleme.size());
            for(int n=0;n<senetlisteleme.size();n++){
                
                v[n] = new Vector();
                String senetNo =null; senetNo= 
            senetlisteleme.get(n).getSenet_no();
            String kurumNo = null;
            kurumNo =senetlisteleme.get(n).getKurum_no();
            v[n].add(senetlisteleme.get(n).getSenet_no());
            String girisTarihi1 = null;
            girisTarihi1 = senetlisteleme.get(n).getGiris_tarih();
            codes.sirketler sk = new codes.sirketler();
            codes.senetler senet = new codes.senetler();
            String kurumAdi = null;
             try {
                kurumAdi = sk.sirketAdiAl(kurumNo);
            } catch (SQLException ex) {
                Logger.getLogger(senetler.class.getName()).log(Level.SEVERE, null, ex);
            }
              if(kurumAdi==null || kurumAdi.length()==0){
                    v[n].add(kurumNo);
                }else
                    v[n].add(kurumAdi);
            List<codes.senetler> detay = null;
            try {
                detay = senet.senet_detay(senetNo);
            } catch (SQLException ex) {
                Logger.getLogger(senetler.class.getName()).log(Level.SEVERE, null, ex);
            }
            for(int j=0;j<detay.size();j++){
  
                v[n].add(detay.get(j).getTutar());
                v[n].add(detay.get(j).getVade());
                v[n].add(girisTarihi1);
                
            }
                sir_tablo.insertRow(n, v[n]);
            }
            jTable1.setModel(sir_tablo);
            jTable1.repaint();
    }//GEN-LAST:event_eldeActionPerformed

    private void hepsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hepsiActionPerformed
        // TODO add your handling code here:
        SenetTumunuGoster();
        elde.setSelected(false);
        giden.setSelected(false);
    }//GEN-LAST:event_hepsiActionPerformed
    private void gidendeneme(){
        DefaultTableModel sir_tablo = (DefaultTableModel) jTable1.getModel();
            sir_tablo.getDataVector().clear();
            sir_tablo.setRowCount(0);
            List<codes.senetler> senetlisteleme = null;//new ArrayList<>();
            try {
                senetlisteleme=new codes.senetler().senet_giden();
            } catch (SQLException ex) {
                Logger.getLogger(senetler.class.getName()).log(Level.SEVERE, null, ex);
            }
            List<codes.senetler> detay = null;
            Vector[] v = new Vector[senetlisteleme.size()];
            for(int n=0;n<senetlisteleme.size();n++){
                v[n] = new Vector();
                String senetNo1 =null; 
                String kurumNo = null; kurumNo =senetlisteleme.get(n).getKurum_no();
                String cikistarihi = senetlisteleme.get(n).getCikis_tarih();
                v[n].add(senetlisteleme.get(n).getSenet_no());
                senetNo1 = senetlisteleme.get(n).getSenet_no();
                 codes.sirketler sirk = new codes.sirketler();
                String kurumad1 = null;
                    try {
                        kurumad1 = sirk.sirketAdiAl(kurumNo);
                    } catch (SQLException ex) {
                        Logger.getLogger(senetler.class.getName()).log(Level.SEVERE, null, ex);
                    }
                     if(kurumad1==null || kurumad1.length()==0){
                    v[n].add(kurumNo);
                    }else
                    v[n].add(kurumad1);
                
            try {
                detay = new codes.senetler().senet_detay(senetNo1);
            } catch (SQLException ex) {
                Logger.getLogger(senetler.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            for(int j=0;j<detay.size();j++){
                v[n].add(detay.get(j).getTutar());
                v[n].add(detay.get(j).getVade());
            }
            v[n].add(cikistarihi);
            sir_tablo.insertRow(n, v[n]);
            }
            jTable1.setModel(sir_tablo);
            jTable1.repaint();
            
    }
    private void gidenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gidenActionPerformed
        // TODO add your handling code here:
        elde.setSelected(false);
        hepsi.setSelected(false);
        
         gidendeneme();
    
    }//GEN-LAST:event_gidenActionPerformed
    public void SenetTumunuGoster(){
        System.gc();
        List<codes.senetler> senetlisteleme = null;//new ArrayList<>();
        DefaultTableModel sir_tablo = (DefaultTableModel) jTable1.getModel();
        sir_tablo.getDataVector().clear();
        sir_tablo.setRowCount(0);
    
        try {
            senetlisteleme=new codes.senetler().tum_senet();
        } catch (Throwable ex) {
            Logger.getLogger(senetler.class.getName()).log(Level.SEVERE, null, ex);
        }
        Vector[] v = new Vector[senetlisteleme.size()];
        for(int n=0;n<senetlisteleme.size();n++){
            v[n] = new Vector();
            v[n].add(senetlisteleme.get(n).getSenet_no());
            String senetNo =null; senetNo= senetlisteleme.get(n).getSenet_no();
            String kurumNo = null; kurumNo =senetlisteleme.get(n).getKurum_no();
            String girisTArihi1 = senetlisteleme.get(n).getGiris_tarih();
            codes.sirketler sk = new codes.sirketler();
            codes.senetler senet = new codes.senetler();
             String kurumAdi = null;
            try {
                kurumAdi = sk.sirketAdiAl(kurumNo);
            } catch (SQLException ex) {
                Logger.getLogger(senetler.class.getName()).log(Level.SEVERE, null, ex);
            }
             if(kurumAdi==null || kurumAdi.length()==0){
                    v[n].add(kurumNo);
                }else
                    v[n].add(kurumAdi);
            
            List<codes.senetler> detay = null;
            try {
                detay = senet.senet_detay(senetNo);
            } catch (SQLException ex) {
                Logger.getLogger(senetler.class.getName()).log(Level.SEVERE, null, ex);
            }
            for(int j=0;j<detay.size();j++){
                v[n].add(detay.get(j).getTutar());
                v[n].add(detay.get(j).getVade());
            }
            v[n].add(girisTArihi1);
            sir_tablo.insertRow(n, v[n]);
        }
        jTable1.setModel(sir_tablo);
        jTable1.repaint();
        System.gc();
    }
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        SenetTumunuGoster();
        
    }//GEN-LAST:event_formComponentShown

    private void eldeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eldeMouseClicked
        
    }//GEN-LAST:event_eldeMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ButtonGroup group = new ButtonGroup();
        group.add(elde);
        group.add(giden);
        group.add(hepsi);
        if(group.getSelection().equals(elde.getModel())) {
            
            
        }
        else if(group.getSelection().equals(giden.getModel())){
           
        }
        else if(group.getSelection().equals(hepsi.getModel())){
            SenetTumunuGoster();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() ==2) {
            String senetNo = null;
      JTable target = (JTable)evt.getSource();
      int row = target.getSelectedRow();
      
        senetNo = jTable1.getValueAt(row, 0).toString();
        gui.senetdetay sdetay = new gui.senetdetay();
                   sdetay.SenetNo = senetNo;
                   System.out.println(senetNo+" "+sdetay.SenetNo);
        JFrame fm = new JFrame("Detay");
        fm.add(sdetay.getContentPane());
        fm.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        fm.setVisible(true);
        sdetay.gosterSenetler();
        fm.pack();
        
      // do some action if appropriate column
    }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(senetler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(senetler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(senetler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(senetler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new senetler().setVisible(true);
             }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton elde;
    private javax.swing.JRadioButton giden;
    private javax.swing.JRadioButton hepsi;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
