/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import static java.time.temporal.TemporalQueries.localDate;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ozkan
 */
public class SirketDetay extends javax.swing.JFrame {

    /**
     * Creates new form SirketDetay
     */
    public SirketDetay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "TUTAR", "TARİH", "İŞLEM TÜRÜ", "AÇIKLAMA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setText("GİRİŞ İŞLEMLERİ");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filtrele", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 12))); // NOI18N

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hepsi", "Nakit İşlemleri", "Çek İşlemleri", "Senet İşlemleri", "Döviz İşlemleri" }));

        jLabel7.setText("İŞLEM TÜRÜ");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel16.setText("-");

        jRadioButton1.setText("YILA GÖRE LİSTELE");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("DÖNEME GÖRE LİSTELE");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AY", "OCAK", "ŞUBAT", "MART", "NİSAN", "MAYIS", "HAZİRAN", "TEMMUZ", "AĞUSTOS", "EYLÜL", "EKİM", "KASIM", "ARALIK" }));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YIL", "Item 2", "Item 3", "Item 4" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jButton1.setText("UYGULA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addGap(33, 33, 33)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jRadioButton2)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sonuçlar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14))); // NOI18N

        jLabel2.setText("Genel Toplam");

        jTextField1.setEnabled(false);

        jLabel3.setText("Nakit Toplam");

        jTextField2.setEnabled(false);

        jLabel4.setText("Çek Toplam");

        jLabel5.setText("Döviz Toplam");

        jLabel6.setText("Senet Toplam");

        jTextField3.setEnabled(false);

        jTextField4.setEnabled(false);

        jTextField5.setEnabled(false);

        jLabel8.setText("Bu Yıl Toplam");

        jTextField6.setEnabled(false);

        jLabel9.setText("Bu Ay Toplam");

        jTextField7.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(jTextField2)
                    .addComponent(jTextField3)
                    .addComponent(jTextField4))
                .addContainerGap(230, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     String Kurum_No="";
     boolean Giris;
     double Nakit_Toplam, Cek_Toplam, Senet_Toplam, Doviz_Toplam, Yil_Toplam, Ay_Toplam, Genel_Toplam;
      DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    LocalDate localDate = LocalDate.now();
    int Yil = localDate.getYear();
    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
       // if(jComboBox2.getSelectedIndex()>0){
          //  this.yil = true;
        //}
    }//GEN-LAST:event_jComboBox2ActionPerformed
    protected void girenSirketler(){
        float GirenToplam = 0.0f;
        DefaultTableModel girentablo = (DefaultTableModel) jTable1.getModel();
        girentablo.getDataVector().clear();
        girentablo.setRowCount(0);
        List<codes.sirketler> sirketlist = null;
        try {
            sirketlist = new codes.sirketler().SirketlerGiren(this.Kurum_No);
        } catch (SQLException ex) {
            Logger.getLogger(sirketler.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Vector[] v = new Vector[sirketlist.size()];
        for(int n=0;n<sirketlist.size();n++){
            v[n] = new Vector();
            v[n].add(sirketlist.get(n).getGenelId());
            v[n].add(sirketlist.get(n).getGenelTutar());
            Genel_Toplam = Genel_Toplam + sirketlist.get(n).getGenelTutar();
            v[n].add(sirketlist.get(n).getGenelTarih());
            String[] temp = sirketlist.get(n).getGenelTarih().split("-");
            int yilim = Integer.parseInt(temp[0]);
            int ay1 = Integer.parseInt(temp[1]);
            if(yilim==localDate.getYear()){
                Yil_Toplam = Yil_Toplam + sirketlist.get(n).getGenelTutar();
            }
            if(ay1 == localDate.getMonthValue() && yilim==localDate.getYear()){
                Ay_Toplam = Ay_Toplam + sirketlist.get(n).getGenelTutar();
            }
            
            v[n].add(sirketlist.get(n).getGenelTuru());
            if(sirketlist.get(n).getGenelTuru().equals("Nakit Girişi")){
                this.Nakit_Toplam = Nakit_Toplam + sirketlist.get(n).getGenelTutar();
            }
            else if(sirketlist.get(n).getGenelTuru().equals("Senet Girişi")){
                this.Senet_Toplam = Senet_Toplam + sirketlist.get(n).getGenelTutar();
            }
            else if(sirketlist.get(n).getGenelTuru().equals("Çek Girişi")){
                this.Cek_Toplam = Cek_Toplam + sirketlist.get(n).getGenelTutar();
            }
            else if(sirketlist.get(n).getGenelTuru().equals("Döviz Girişi")){
                this.Doviz_Toplam = Doviz_Toplam + sirketlist.get(n).getGenelTutar();
            }
            v[n].add(sirketlist.get(n).getGenelAciklama());
            girentablo.insertRow(n, v[n]);
        }
        jTable1.setModel(girentablo);
         jTable1.repaint();
         
    }
     protected void cikanSirketler(){
        int CikanToplam = 0;
        DefaultTableModel cikantablo = (DefaultTableModel) jTable1.getModel();
        cikantablo.getDataVector().clear();
        cikantablo.setRowCount(0);
        List<codes.sirketler> sirklist1 = null;
        codes.sirketler sl = new codes.sirketler();
        try {
            sirklist1 = sl.SirketlerCikan(this.Kurum_No);
        } catch (SQLException ex) {
            Logger.getLogger(sirketler.class.getName()).log(Level.SEVERE, null, ex);
        }
          if(sirklist1.size()>0){
            Vector[] v1 = new Vector[sirklist1.size()];
            for(int n=0;n<v1.length;n++){
            v1[n] = new Vector();
            String[] temp = sirklist1.get(n).getGenelCikanTarih().split("-");
            int yilim = Integer.parseInt(temp[0]);
            int ay1 = Integer.parseInt(temp[1]);
            if(yilim==localDate.getYear()){
                Yil_Toplam = Yil_Toplam + sirklist1.get(n).getGenelCikanTutar();
            }
            if(ay1 == localDate.getMonthValue() && yilim==localDate.getYear()){
                Ay_Toplam = Ay_Toplam + sirklist1.get(n).getGenelCikanTutar();
            }
            v1[n].add(sirklist1.get(n).getGenelCikanId());
            v1[n].add(sirklist1.get(n).getGenelCikanTutar());
            Genel_Toplam = Genel_Toplam + sirklist1.get(n).getGenelCikanTutar();
             if(sirklist1.get(n).getGenelCikanTuru().equals("Nakit Çıkışı")){
                this.Nakit_Toplam = Nakit_Toplam + sirklist1.get(n).getGenelCikanTutar();
            }
             else if(sirklist1.get(n).getGenelCikanTuru().equals("Çek Çıkışı")){
                 this.Cek_Toplam = Cek_Toplam + sirklist1.get(n).getGenelCikanTutar();
             }
             else if(sirklist1.get(n).getGenelCikanTuru().equals("Senet Çıkışı")){
                 this.Senet_Toplam = Senet_Toplam + sirklist1.get(n).getGenelCikanTutar();
             }
             else if(sirklist1.get(n).getGenelTuru().equals("Döviz Çıkışı")){
                 this.Doviz_Toplam = Doviz_Toplam + sirklist1.get(n).getGenelCikanTutar();
             }
            v1[n].add(sirklist1.get(n).getGenelCikanTarih());
            v1[n].add(sirklist1.get(n).getGenelCikanTuru());
            v1[n].add(sirklist1.get(n).getGenelCikanAciklama());
            cikantablo.insertRow(n, v1[n]);
            
            }
        }
          jTable1.setModel(cikantablo);
          jTable1.repaint();
          
    }
     protected void cikanSirketlerYilaGore(){
        int CikanToplam = 0;
        DefaultTableModel cikantablo = (DefaultTableModel) jTable1.getModel();
        cikantablo.getDataVector().clear();
        cikantablo.setRowCount(0);
        List<codes.sirketler> sirklist1 = null;
        codes.sirketler sl = new codes.sirketler();
        int yil = Integer.parseInt(jComboBox2.getSelectedItem().toString().trim());
        try {
            sirklist1 = sl.SirketlerCikanYilaGore(this.Kurum_No, yil);
        } catch (SQLException ex) {
            Logger.getLogger(sirketler.class.getName()).log(Level.SEVERE, null, ex);
        }
          if(sirklist1.size()>0){
            Vector[] v1 = new Vector[sirklist1.size()];
            for(int n=0;n<v1.length;n++){
            v1[n] = new Vector();
            v1[n].add(sirklist1.get(n).getGenelCikanId());
            v1[n].add(sirklist1.get(n).getGenelCikanTutar());
            Genel_Toplam = Genel_Toplam + sirklist1.get(n).getGenelCikanTutar();
             if(sirklist1.get(n).getGenelCikanTuru().equals("Nakit Çıkışı")){
                this.Nakit_Toplam = Nakit_Toplam + sirklist1.get(n).getGenelCikanTutar();
            }
             else if(sirklist1.get(n).getGenelCikanTuru().equals("Çek Çıkışı")){
                 this.Cek_Toplam = Cek_Toplam + sirklist1.get(n).getGenelCikanTutar();
             }
             else if(sirklist1.get(n).getGenelCikanTuru().equals("Senet Çıkışı")){
                 this.Senet_Toplam = Senet_Toplam + sirklist1.get(n).getGenelCikanTutar();
             }
             else if(sirklist1.get(n).getGenelTuru().equals("Döviz Çıkışı")){
                 this.Doviz_Toplam = Doviz_Toplam + sirklist1.get(n).getGenelCikanTutar();
             }
            v1[n].add(sirklist1.get(n).getGenelCikanTarih());
            v1[n].add(sirklist1.get(n).getGenelCikanTuru());
            v1[n].add(sirklist1.get(n).getGenelCikanAciklama());
            cikantablo.insertRow(n, v1[n]);
            
            }
        }
          jTable1.setModel(cikantablo);
          jTable1.repaint();
          
    }
     protected void cikanSirketlerAyveYilaGore(){
        int CikanToplam = 0;
        DefaultTableModel cikantablo = (DefaultTableModel) jTable1.getModel();
        cikantablo.getDataVector().clear();
        cikantablo.setRowCount(0);
        List<codes.sirketler> sirklist1 = null;
        codes.sirketler sl = new codes.sirketler();
        int yil = Integer.parseInt(jComboBox4.getSelectedItem().toString().trim());
        int ay = jComboBox1.getSelectedIndex();
        try {
            sirklist1 = sl.SirketlerCikanAyveYila(Kurum_No, ay, yil);
        } catch (SQLException ex) {
            Logger.getLogger(sirketler.class.getName()).log(Level.SEVERE, null, ex);
        }
          if(sirklist1.size()>0){
            Vector[] v1 = new Vector[sirklist1.size()];
            for(int n=0;n<v1.length;n++){
            v1[n] = new Vector();
            v1[n].add(sirklist1.get(n).getGenelCikanId());
            v1[n].add(sirklist1.get(n).getGenelCikanTutar());
            Genel_Toplam = Genel_Toplam + sirklist1.get(n).getGenelCikanTutar();
             if(sirklist1.get(n).getGenelCikanTuru().equals("Nakit Çıkışı")){
                this.Nakit_Toplam = Nakit_Toplam + sirklist1.get(n).getGenelCikanTutar();
            }
             else if(sirklist1.get(n).getGenelCikanTuru().equals("Çek Çıkışı")){
                 this.Cek_Toplam = Cek_Toplam + sirklist1.get(n).getGenelCikanTutar();
             }
             else if(sirklist1.get(n).getGenelCikanTuru().equals("Senet Çıkışı")){
                 this.Senet_Toplam = Senet_Toplam + sirklist1.get(n).getGenelCikanTutar();
             }
             else if(sirklist1.get(n).getGenelTuru().equals("Döviz Çıkışı")){
                 this.Doviz_Toplam = Doviz_Toplam + sirklist1.get(n).getGenelCikanTutar();
             }
            v1[n].add(sirklist1.get(n).getGenelCikanTarih());
            v1[n].add(sirklist1.get(n).getGenelCikanTuru());
            v1[n].add(sirklist1.get(n).getGenelCikanAciklama());
            cikantablo.insertRow(n, v1[n]);
            
            }
        }
          jTable1.setModel(cikantablo);
          jTable1.repaint();
          
    }
    public void detayAcilis(){
        girenSirketler();
        
        DefaultComboBoxModel combo = new DefaultComboBoxModel();
            combo.addElement("YIL SEÇİNİZ");
            for(int i=localDate.getYear();i>=1995;i--){
                combo.addElement(i);
            }
            jComboBox2.setModel(combo);
            jComboBox2.repaint();
            jComboBox4.setModel(combo);
            jComboBox4.repaint();
            jTextField2.setText(String.valueOf(this.Nakit_Toplam));
            jTextField3.setText(String.valueOf(this.Cek_Toplam));
            jTextField4.setText(String.valueOf(this.Doviz_Toplam));
            jTextField5.setText(String.valueOf(this.Senet_Toplam));
            jTextField1.setText(String.valueOf(Genel_Toplam));
            jTextField6.setText(String.valueOf(this.Yil_Toplam));
            jTextField7.setText(String.valueOf(this.Ay_Toplam));
    }
    public void detayCikisAcilis(){
        cikanSirketler();
        System.out.println(this.Giris);
        DefaultComboBoxModel combo = new DefaultComboBoxModel();
            combo.addElement("YIL SEÇİNİZ");
            for(int i=localDate.getYear();i>=1995;i--){
                combo.addElement(i);
            }
            jComboBox2.setModel(combo);
            jComboBox2.repaint();
            jComboBox4.setModel(combo);
            jComboBox4.repaint();
            jTextField2.setText(String.valueOf(this.Nakit_Toplam));
            jTextField3.setText(String.valueOf(this.Cek_Toplam));
            jTextField4.setText(String.valueOf(this.Doviz_Toplam));
            jTextField5.setText(String.valueOf(this.Senet_Toplam));
            jTextField1.setText(String.valueOf(Genel_Toplam));
            jTextField6.setText(String.valueOf(this.Yil_Toplam));
            jTextField7.setText(String.valueOf(this.Ay_Toplam));
    }
    protected void girenSirketlerYilaGore(){
        float GirenToplam = 0.0f;
        DefaultTableModel girentablo = (DefaultTableModel) jTable1.getModel();
        girentablo.getDataVector().clear();
        girentablo.setRowCount(0);
        List<codes.sirketler> sirketlist = null;
        int yil = Integer.parseInt(jComboBox2.getSelectedItem().toString().trim());
        try {
            sirketlist = new codes.sirketler().SirketlerGirenYilaGöre(this.Kurum_No, yil);
        } catch (SQLException ex) {
            Logger.getLogger(sirketler.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Vector[] v = new Vector[sirketlist.size()];
        for(int n=0;n<sirketlist.size();n++){
            v[n] = new Vector();
            v[n].add(sirketlist.get(n).getGenelId());
            v[n].add(sirketlist.get(n).getGenelTutar());
            Genel_Toplam = Genel_Toplam + sirketlist.get(n).getGenelTutar();
            if(sirketlist.get(n).getGenelTuru().equals("Nakit Girişi")){
                this.Nakit_Toplam = Nakit_Toplam + sirketlist.get(n).getGenelTutar();
            }
            else if(sirketlist.get(n).getGenelTuru().equals("Senet Girişi")){
                this.Senet_Toplam = Senet_Toplam + sirketlist.get(n).getGenelTutar();
            }
            else if(sirketlist.get(n).getGenelTuru().equals("Çek Girişi")){
                this.Cek_Toplam = Cek_Toplam + sirketlist.get(n).getGenelTutar();
            }
            else if(sirketlist.get(n).getGenelTuru().equals("Döviz Girişi")){
                this.Doviz_Toplam = Doviz_Toplam + sirketlist.get(n).getGenelTutar();
            }
            v[n].add(sirketlist.get(n).getGenelTarih());
            v[n].add(sirketlist.get(n).getGenelTuru());
            v[n].add(sirketlist.get(n).getGenelAciklama());
            girentablo.insertRow(n, v[n]);
        }
        jTable1.setModel(girentablo);
         jTable1.repaint();
        
    }
    protected void girenSirketAyveYil(){
        float GirenToplam = 0.0f;
        DefaultTableModel girentablo = (DefaultTableModel) jTable1.getModel();
        girentablo.getDataVector().clear();
        girentablo.setRowCount(0);
        List<codes.sirketler> sirketlist = null;
        int yil = Integer.parseInt(jComboBox4.getSelectedItem().toString().trim());
        int ay = jComboBox1.getSelectedIndex();
        try {
            sirketlist = new codes.sirketler().SirketlerGirenAyveYil(Kurum_No, ay, yil);
        } catch (SQLException ex) {
            Logger.getLogger(sirketler.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Vector[] v = new Vector[sirketlist.size()];
        for(int n=0;n<sirketlist.size();n++){
            v[n] = new Vector();
            v[n].add(sirketlist.get(n).getGenelId());
            v[n].add(sirketlist.get(n).getGenelTutar());
            Genel_Toplam = Genel_Toplam + sirketlist.get(n).getGenelTutar();
            if(sirketlist.get(n).getGenelTuru().equals("Nakit Girişi")){
                this.Nakit_Toplam = Nakit_Toplam + sirketlist.get(n).getGenelTutar();
            }
            else if(sirketlist.get(n).getGenelTuru().equals("Senet Girişi")){
                this.Senet_Toplam = Senet_Toplam + sirketlist.get(n).getGenelTutar();
            }
            else if(sirketlist.get(n).getGenelTuru().equals("Çek Girişi")){
                this.Cek_Toplam = Cek_Toplam + sirketlist.get(n).getGenelTutar();
            }
            else if(sirketlist.get(n).getGenelTuru().equals("Döviz Girişi")){
                this.Doviz_Toplam = Doviz_Toplam + sirketlist.get(n).getGenelTutar();
            }
            v[n].add(sirketlist.get(n).getGenelTarih());
            v[n].add(sirketlist.get(n).getGenelTuru());
            v[n].add(sirketlist.get(n).getGenelAciklama());
            girentablo.insertRow(n, v[n]);
        }
        jTable1.setModel(girentablo);
         jTable1.repaint();
        
    }
    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        jRadioButton2.setSelected(false);
       // jFormattedTextField2.setEnabled(false);
       // jFormattedTextField3.setEnabled(false);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        jRadioButton1.setSelected(false);
       // jFormattedTextField2.setEnabled(true);
        //jFormattedTextField3.setEnabled(true);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        girenSirketler();
    }//GEN-LAST:event_formComponentShown

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.Nakit_Toplam=0;
        this.Cek_Toplam=0;
        this.Senet_Toplam=0;
        this.Doviz_Toplam=0;
        this.Genel_Toplam=0;
        if(this.Giris){
            if(jComboBox2.getSelectedIndex()>0 && jRadioButton1.isSelected()){
                girenSirketlerYilaGore();
            }
            else if(jRadioButton2.isSelected() && jRadioButton2.isSelected()){
                girenSirketAyveYil();
        }else{
                if(jComboBox2.getSelectedIndex()>0 && jRadioButton1.isSelected()){
                    cikanSirketlerYilaGore();
                }
                else if(jRadioButton2.isSelected() && jComboBox1.getSelectedIndex()>0){
                  cikanSirketlerAyveYilaGore();
                }
            } 
        }
        if(jComboBox2.getSelectedIndex()>0){
            girenSirketlerYilaGore();
        }
        else if(jRadioButton2.isSelected()){
            girenSirketAyveYil();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SirketDetay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SirketDetay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SirketDetay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SirketDetay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SirketDetay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
