/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.File;
import java.io.IOException;
import java.sql.Date;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.stage.FileChooser;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ozkan
 */
public class sirketler extends javax.swing.JFrame {

    /**
     * Creates new form sirketler
     */
    public sirketler() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        jFileChooser1.setCurrentDirectory(new java.io.File("C:\\"));

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            addComponentListener(new java.awt.event.ComponentAdapter() {
                public void componentShown(java.awt.event.ComponentEvent evt) {
                    formComponentShown(evt);
                }
            });

            jTable2.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null}
                },
                new String [] {
                    "İŞLEM NUMARASI", "TUTAR", "TARİH", "İŞLEM TÜRÜ", "AÇIKLAMA"
                }
            ));
            jScrollPane3.setViewportView(jTable2);

            jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
            jLabel10.setText("VERİLEN");

            jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
            jLabel11.setText("ALINAN");

            jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
            jComboBox1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jComboBox1ActionPerformed(evt);
                }
            });

            jLabel12.setText("ŞİRKET SEÇİNİZ");

            jButton4.setText("LİSTELE");
            jButton4.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton4ActionPerformed(evt);
                }
            });

            jLabel1.setText("Şirketler Sayfası");

            jLabel2.setText("Giren Toplam:");

            jTextField1.setEnabled(false);

            jLabel3.setText("Çıkan Toplam");

            jTextField2.setEnabled(false);

            jButton1.setText("EXCEL'E AKTAR");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            jButton2.setText("YAZDIR");

            jTable3.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null},
                    {null, null, null, null, null}
                },
                new String [] {
                    "İŞLEM NUMARASI", "TUTAR", "TARİH", "İŞLEM TÜRÜ", "AÇIKLAMA"
                }
            ));
            jScrollPane4.setViewportView(jTable3);

            jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hepsi", "Nakit İşlemleri", "Çek İşlemleri", "Senet İşlemleri", "Döviz İşlemleri" }));

            jLabel4.setText("İŞLEM TÜRÜ");

            jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder());

            jFormattedTextField2.setColumns(3);
            try {
                jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
            } catch (java.text.ParseException ex) {
                ex.printStackTrace();
            }
            jFormattedTextField2.setEnabled(false);

            jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
            jComboBox2.setEnabled(false);
            jComboBox2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jComboBox2ActionPerformed(evt);
                }
            });

            jLabel16.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
            jLabel16.setText("-");

            try {
                jFormattedTextField3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
            } catch (java.text.ParseException ex) {
                ex.printStackTrace();
            }
            jFormattedTextField3.setEnabled(false);

            jLabel5.setText("TARİH FİLTRELERİ");

            jRadioButton1.setText("YILA GÖRE LİSTELE");
            jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jRadioButton1ActionPerformed(evt);
                }
            });

            jRadioButton2.setText("TARİH ARALIĞINDA LİSTELE");
            jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jRadioButton2ActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(126, 126, 126)
                            .addComponent(jLabel5)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jRadioButton1)
                                .addComponent(jRadioButton2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(3, 3, 3)
                                    .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(40, 40, 40))))
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jRadioButton1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)
                        .addComponent(jRadioButton2))
                    .addContainerGap())
            );

            jButton3.setText("TAM EKRAN");
            jButton3.setEnabled(false);
            jButton3.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton3ActionPerformed(evt);
                }
            });

            jButton5.setText("TAM EKRAN");
            jButton5.setEnabled(false);
            jButton5.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton5ActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2)
                    .addGap(18, 18, 18)
                    .addComponent(jButton1)
                    .addGap(479, 479, 479))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(240, 240, 240)
                            .addComponent(jLabel13))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 1057, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel4))
                                    .addGap(74, 74, 74)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(344, 344, 344)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jButton3)
                                            .addGap(147, 147, 147)
                                            .addComponent(jLabel11))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel3)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jScrollPane3)))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jButton5)
                                            .addGap(182, 182, 182)
                                            .addComponent(jLabel10))
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addContainerGap(303, Short.MAX_VALUE))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel12))
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel4))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(33, 33, 33)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jButton4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                    .addComponent(jLabel13)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2))
                    .addGap(18, 18, 18)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(jButton3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(jButton5))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap())
            );

            jScrollPane1.setViewportView(jPanel1);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1108, Short.MAX_VALUE)
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
                    .addContainerGap())
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents
    String kurumNo = null;
    boolean yil = false;
    DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    LocalDate localDate = LocalDate.now();
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(!this.kurumNo.equals("")){
            jButton3.setEnabled(true);
            jButton5.setEnabled(true);
        }
        if(this.yil && jRadioButton1.isSelected()){
            if(jComboBox2.getSelectedIndex()>0){
                girenSirketlerYilaGore();
                cikanSirketlerYilaGore();
                this.yil = false;
        }else if(jRadioButton2.isSelected() && !jFormattedTextField2.getText().equals("") && !jFormattedTextField3.getText().equals("")){
                String[] tarihk = jFormattedTextField2.getText().trim().split("/");
                String[] tarihb = jFormattedTextField3.getText().trim().split("/");
                String tarih1 = tarihk[2]+tarihk[1]+tarihk[0];
                String tarih2 = tarihb[2]+tarihb[1]+tarihb[0];
                girenSirketlerTarihAraligi(tarih1, tarih2);
                cikanSirketlerTarihAraligi(tarih1, tarih2);
        }
        }
        else{
             girenSirketler();
             cikanSirketler();
        }
        if(jComboBox3.getSelectedIndex()>0){
            String tur = null, tur2 = null;
            if(jComboBox1.getSelectedIndex()==1){
                tur = "Döviz Girişi";
                tur2 = "Bankadan Nakit Çıkış";
            }
            girenSirketler();
            cikanSirketler();
            DefaultTableModel tablo = (DefaultTableModel)jTable2.getModel();
            int limit = jTable2.getRowCount();
            for(int i=0;i<=limit;i++ ){
                String a = null;
                a = jTable2.getValueAt(i, 3).toString().trim();
                a = a.substring(0, 1);
                System.out.println(a);
                if(!a.equals("B")){
                    tablo.removeRow(i);
                }
            }
            jTable2.setModel(tablo);
            jTable2.repaint();
        }
       
         
    }//GEN-LAST:event_jButton4ActionPerformed
    protected void girenSirketler(){
        float GirenToplam = 0.0f;
        DefaultTableModel girentablo = (DefaultTableModel) jTable2.getModel();
        girentablo.getDataVector().clear();
        girentablo.setRowCount(0);
        List<codes.sirketler> sirketlist = null;
        try {
            sirketlist = new codes.sirketler().SirketlerGiren(this.kurumNo);
        } catch (SQLException ex) {
            Logger.getLogger(sirketler.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Vector[] v = new Vector[sirketlist.size()];
        for(int n=0;n<sirketlist.size();n++){
            v[n] = new Vector();
            v[n].add(sirketlist.get(n).getGenelId());
            v[n].add(sirketlist.get(n).getGenelTutar());
            GirenToplam = GirenToplam + sirketlist.get(n).getGenelTutar();
            v[n].add(sirketlist.get(n).getGenelTarih());
            v[n].add(sirketlist.get(n).getGenelTuru());
            v[n].add(sirketlist.get(n).getGenelAciklama());
            girentablo.insertRow(n, v[n]);
        }
        jTable2.setModel(girentablo);
         jTable2.repaint();
         jTextField1.setText(String.valueOf(GirenToplam));
    }
        protected void girenSirketlerYilaGore(){
        float GirenToplam = 0.0f;
        DefaultTableModel girentablo = (DefaultTableModel) jTable2.getModel();
        girentablo.getDataVector().clear();
        girentablo.setRowCount(0);
        List<codes.sirketler> sirketlist = null;
        int yil = Integer.parseInt(jComboBox2.getSelectedItem().toString().trim());
        try {
            sirketlist = new codes.sirketler().SirketlerGirenYilaGöre(this.kurumNo, yil);
        } catch (SQLException ex) {
            Logger.getLogger(sirketler.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Vector[] v = new Vector[sirketlist.size()];
        for(int n=0;n<sirketlist.size();n++){
            v[n] = new Vector();
            v[n].add(sirketlist.get(n).getGenelId());
            v[n].add(sirketlist.get(n).getGenelTutar());
            GirenToplam = GirenToplam + sirketlist.get(n).getGenelTutar();
            v[n].add(sirketlist.get(n).getGenelTarih());
            v[n].add(sirketlist.get(n).getGenelTuru());
            v[n].add(sirketlist.get(n).getGenelAciklama());
            girentablo.insertRow(n, v[n]);
        }
        jTable2.setModel(girentablo);
         jTable2.repaint();
         jTextField1.setText(String.valueOf(GirenToplam));
    }
        
        protected void girenSirketlerTarihAraligi(String tarih1,String tarih2){
        float GirenToplam = 0.0f;
        DefaultTableModel girentablo = (DefaultTableModel) jTable2.getModel();
        girentablo.getDataVector().clear();
        girentablo.setRowCount(0);
        List<codes.sirketler> sirketlist = null;
        int yil = Integer.parseInt(jComboBox2.getSelectedItem().toString().trim());
        try {
            sirketlist = new codes.sirketler().SirketlerGirenTarihAraligi(kurumNo, tarih1, tarih2);
        } catch (SQLException ex) {
            Logger.getLogger(sirketler.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Vector[] v = new Vector[sirketlist.size()];
        for(int n=0;n<sirketlist.size();n++){
            v[n] = new Vector();
            v[n].add(sirketlist.get(n).getGenelId());
            v[n].add(sirketlist.get(n).getGenelTutar());
            GirenToplam = GirenToplam + sirketlist.get(n).getGenelTutar();
            v[n].add(sirketlist.get(n).getGenelTarih());
            v[n].add(sirketlist.get(n).getGenelTuru());
            v[n].add(sirketlist.get(n).getGenelAciklama());
            girentablo.insertRow(n, v[n]);
        }
        jTable2.setModel(girentablo);
         jTable2.repaint();
         jTextField1.setText(String.valueOf(GirenToplam));
    }
    protected void cikanSirketler(){
        int CikanToplam = 0;
        DefaultTableModel cikantablo = (DefaultTableModel) jTable3.getModel();
        cikantablo.getDataVector().clear();
        cikantablo.setRowCount(0);
        List<codes.sirketler> sirklist1 = null;
        codes.sirketler sl = new codes.sirketler();
        try {
            sirklist1 = sl.SirketlerCikan(this.kurumNo);
        } catch (SQLException ex) {
            Logger.getLogger(sirketler.class.getName()).log(Level.SEVERE, null, ex);
        }
          if(sirklist1.size()>0){
            Vector[] v1 = new Vector[sirklist1.size()];
            for(int n=0;n<v1.length;n++){
            v1[n] = new Vector();
            v1[n].add(sirklist1.get(n).getGenelCikanId());
            v1[n].add(sirklist1.get(n).getGenelCikanTutar());
            CikanToplam = CikanToplam + sirklist1.get(n).getGenelCikanTutar();
            v1[n].add(sirklist1.get(n).getGenelCikanTarih());
            v1[n].add(sirklist1.get(n).getGenelCikanTuru());
            v1[n].add(sirklist1.get(n).getGenelCikanAciklama());
            cikantablo.insertRow(n, v1[n]);
            
            }
        }
          jTable3.setModel(cikantablo);
          jTable3.repaint();
          jTextField2.setText(String.valueOf(CikanToplam));
    }
     protected void cikanSirketlerYilaGore(){
        int CikanToplam = 0;
        DefaultTableModel cikantablo = (DefaultTableModel) jTable3.getModel();
        cikantablo.getDataVector().clear();
        cikantablo.setRowCount(0);
        List<codes.sirketler> sirklist1 = null;
        codes.sirketler sl = new codes.sirketler();
        int yil = Integer.parseInt(jComboBox2.getSelectedItem().toString().trim());
        try {
            sirklist1 = sl.SirketlerCikanYilaGore(this.kurumNo, yil);
        } catch (SQLException ex) {
            Logger.getLogger(sirketler.class.getName()).log(Level.SEVERE, null, ex);
        }
          if(sirklist1.size()>0){
            Vector[] v1 = new Vector[sirklist1.size()];
            for(int n=0;n<v1.length;n++){
            v1[n] = new Vector();
            v1[n].add(sirklist1.get(n).getGenelCikanId());
            v1[n].add(sirklist1.get(n).getGenelCikanTutar());
            CikanToplam = CikanToplam + sirklist1.get(n).getGenelCikanTutar();
            v1[n].add(sirklist1.get(n).getGenelCikanTarih());
            v1[n].add(sirklist1.get(n).getGenelCikanTuru());
            v1[n].add(sirklist1.get(n).getGenelCikanAciklama());
            cikantablo.insertRow(n, v1[n]);
            
            }
        }
          jTable3.setModel(cikantablo);
          jTable3.repaint();
          jTextField2.setText(String.valueOf(CikanToplam));
    }
       protected void cikanSirketlerTarihAraligi(String tarih1, String tarih2){
        int CikanToplam = 0;
        DefaultTableModel cikantablo = (DefaultTableModel) jTable3.getModel();
        cikantablo.getDataVector().clear();
        cikantablo.setRowCount(0);
        List<codes.sirketler> sirklist1 = null;
        codes.sirketler sl = new codes.sirketler();
        int yil = Integer.parseInt(jComboBox2.getSelectedItem().toString().trim());
        try {
            sirklist1 = sl.SirketlerGirenTarihAraligi(kurumNo, tarih1, tarih2);
        } catch (SQLException ex) {
            Logger.getLogger(sirketler.class.getName()).log(Level.SEVERE, null, ex);
        }
          if(sirklist1.size()>0){
            Vector[] v1 = new Vector[sirklist1.size()];
            for(int n=0;n<v1.length;n++){
            v1[n] = new Vector();
            v1[n].add(sirklist1.get(n).getGenelCikanId());
            v1[n].add(sirklist1.get(n).getGenelCikanTutar());
            CikanToplam = CikanToplam + sirklist1.get(n).getGenelCikanTutar();
            v1[n].add(sirklist1.get(n).getGenelCikanTarih());
            v1[n].add(sirklist1.get(n).getGenelCikanTuru());
            v1[n].add(sirklist1.get(n).getGenelCikanAciklama());
            cikantablo.insertRow(n, v1[n]);
            
            }
        }
          jTable3.setModel(cikantablo);
          jTable3.repaint();
          jTextField2.setText(String.valueOf(CikanToplam));
    }
    
    public void sirketlerAcilis(){
        
        List<codes.sirketler> sirketlist = null;//new ArrayList<>();
        DefaultComboBoxModel comboBoxModel = new DefaultComboBoxModel();
        comboBoxModel.addElement("Lütfen Şirket Seçiniz");
        try {
            sirketlist = new codes.sirketler().sirketListesi();
        } catch (SQLException ex) {
            Logger.getLogger(kasa.class.getName()).log(Level.SEVERE, null, ex);
        }
            ArrayList<String> listem = new ArrayList();
            for(int n=0;n<sirketlist.size();n++){
                //jComboBox2.addItem(sirketlist.get(n).getS_adi());
                 //comboBoxModel.addElement(sirketlist.get(n).getS_adi());
                 listem.add(sirketlist.get(n).getS_adi());
            }
            for(int i=0;i<listem.size();i++){
                comboBoxModel.addElement(listem.get(i));
            }
            jComboBox1.setModel(comboBoxModel);
            jComboBox1.repaint();
            
            ////////YILLARIN COMBOBOXA ALINMASI/////////
            DefaultComboBoxModel combo = new DefaultComboBoxModel();
            combo.addElement("YIL SEÇİNİZ");
            for(int i=localDate.getYear();i>=1995;i--){
                combo.addElement(i);
            }
            jComboBox2.setModel(combo);
            jComboBox2.repaint();
            
            ///////////jformatted textler////////////
            jFormattedTextField2.setText(dtf.format(localDate));
            jFormattedTextField3.setText(dtf.format(localDate));
            
    }
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        sirketlerAcilis();
                
    }//GEN-LAST:event_formComponentShown
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        codes.sirketler sk = new codes.sirketler();
        try {
            this.kurumNo = sk.sicilAl(jComboBox1.getSelectedItem().toString());
        } catch (SQLException ex) {
            Logger.getLogger(sirketler.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
       
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        if(jComboBox2.getSelectedIndex()>0){
            this.yil = true;
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        jRadioButton2.setSelected(false);
        jFormattedTextField2.setEnabled(false);
        jFormattedTextField3.setEnabled(false);
        jComboBox2.setEnabled(true);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        jRadioButton1.setSelected(false);
        jFormattedTextField2.setEnabled(true);
        jFormattedTextField3.setEnabled(true);
        jComboBox2.setEnabled(false);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int returnVal = jFileChooser1.showOpenDialog(this);
         jFileChooser1.setFileSelectionMode(JFileChooser.FILES_ONLY);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = (File) jFileChooser1.getSelectedFile().getAbsoluteFile();
            codes.sirketler ex= new codes.sirketler();
           // File file =new File("C:\\Users\\ozkan\\Desktop\\bankalar.xlsx");
                System.out.println(file);
            
             try {
                 ex.exportTable(jTable2, file);
                 //}      
             } catch (IOException ex1) {
                 Logger.getLogger(KasaListele.class.getName()).log(Level.SEVERE, null, ex1);
         
             }
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        gui.SirketDetay detay = new gui.SirketDetay();
        JFrame fm = new JFrame();
        fm.add(detay.getContentPane());
        fm.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        fm.setVisible(true);
        detay.Kurum_No=this.kurumNo;
        detay.detayAcilis();
        detay.Giris=true;
        fm.setTitle("Cari Detay-Giren");
        fm.pack();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         gui.SirketDetay detay = new gui.SirketDetay();
        JFrame fm = new JFrame();
        fm.add(detay.getContentPane());
        fm.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        fm.setVisible(true);
        detay.Kurum_No=this.kurumNo;
        detay.detayCikisAcilis();
        detay.Giris=false;
        fm.setTitle("Cari Detay-Çıkan");
        fm.pack();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sirketler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sirketler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sirketler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sirketler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sirketler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
